### ISSUE TITLE
3.0.1 - JiraCookieAuth - TypeError: session() takes 1 positional argument but 2 were given  when creating a JIRA instance with auth=(username,password)

### ISSUE THREAD

**Issue by tevert** [pycontribs/jira#1035]
Before raising any bug be sure that you used the latest release and that it still reproduces with the latest master. No other version is supported.

**Describe the bug**
Using the new package published an hour ago, I get a runtime arg error when opening a connection. 

**To Reproduce**
```
$ python3                                                                                              
Python 3.8.5 (default, Jan 27 2021, 15:41:15)                                                          
[GCC 9.3.0] on linux                                                                                   
Type "help", "copyright", "credits" or "license" for more information.                                 
>>> from jira import JIRA                                                                              
>>> username = 'tevert@motus.com'                                                                      
>>> password = '<REDACTED>'                                                                           
>>> conn = JIRA('https://jira.motus.com', auth = (username, password))                                 
Traceback (most recent call last):                                                                     
  File "<stdin>", line 1, in <module>                                                                  
  File "/home/tevert/.local/lib/python3.8/site-packages/jira/client.py", line 496, in __init__         
    user = self.session()                                                                              
  File "/home/tevert/.local/lib/python3.8/site-packages/jira/client.py", line 2980, in session         
    r = self._session.get(url)                                                                         
  File "/home/tevert/.local/lib/python3.8/site-packages/jira/resilientsession.py", line 172, in get    
    return self.__verb("GET", url, **kwargs)                                                           
  File "/home/tevert/.local/lib/python3.8/site-packages/jira/resilientsession.py", line 143, in __verb 
    response = method(url, timeout=self.timeout, **kwargs)                                             
  File "/home/tevert/.local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get        
    return self.request('GET', url, **kwargs)                                                          
  File "/home/tevert/.local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request    
    resp = self.send(prep, **send_kwargs)                                                              
  File "/home/tevert/.local/lib/python3.8/site-packages/requests/sessions.py", line 650, in send       
    r = dispatch_hook('response', hooks, r, **kwargs)                                                  
  File "/home/tevert/.local/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook  
    _hook_data = hook(hook_data, **kwargs)                                                             
  File "/home/tevert/.local/lib/python3.8/site-packages/jira/client.py", line 199, in handle_401       
    self.init_session()                                                                                
  File "/home/tevert/.local/lib/python3.8/site-packages/jira/client.py", line 215, in init_session     
    self.start_session()                                                                               
  File "/home/tevert/.local/lib/python3.8/site-packages/jira/client.py", line 229, in start_session    
    self._get_session(self.__auth)                                                                     
TypeError: session() takes 1 positional argument but 2 were given                                      
>>>                                                                                                    
```
1. Any additional steps or considerations that happen before or after.

**Expected behavior**
I get a connection

**Stack Trace**
```
A code block with the any trace messages.
```

**Version Information**
Type of Jira instance:
- [  ] Jira Cloud (Hosted by Atlassian)
- [ X ] Jira Server or Data Center (Self-hosted)
Python Interpreter: 3.8
jira-python: 3..0.1
OS: WSL Ubuntu
IPython (Optional): <VERSION>
Other Dependencies:

**Additional context**

**Comment by tevert** [comment]
To clarify, this exact code was working fine this morning with version 2.0.0

**Comment by studioj** [comment]
Thx for your issue. I'll help investigate this afternoon.

**Comment by studioj** [comment]
I can repro => that's a start

**Comment by studioj** [comment]
i think the "auth" parameter was "potentionaly" misused in prev versions

could you try

`conn = JIRA('https://jira.motus.com', basic_auth=(username, password))  `

**Comment by studioj** [comment]
created a branch with a test testing this. 
https://github.com/pycontribs/jira/tree/auth_parameter_is_not_working_as_it_was_before_1035
of course its failing:
https://github.com/pycontribs/jira/runs/2576091588?check_suite_focus=true#step:9:618

**Comment by tevert** [comment]
`basic_auth` works fine, thanks for the quick update!

**Comment by studioj** [comment]
@ssbarnea maybe we should instead add a warning that its deprecated

**Comment by dogasantos** [comment]
+1 on cookie based auth.
I have an instance with generic basic_auth in front of Jira for additional security layer.
ty

**Comment by studioj** [comment]
@ssbarnea cookie based login is still broken for jira server... 
Was this automatically closed?

**Comment by ssbarnea** [comment]
Based on what I see on screen it seems that that merge did close this ticket even if it did not had a "fixes: #num" block on it. A glitch in the github matrix?
