### ISSUE TITLE
SSLError raised by requests causes follow-on AttributeError

### ISSUE THREAD

**Issue by andy-maier** [pycontribs/jira#1158]
**Describe the bug**

Creating a `JIRA` object for a Jira server that fails certificate verification results in a follow-on error:
```
  File "/Users/maiera/virtualenvs/iaas39/lib/python3.9/site-packages/jira/resilientsession.py", line 120, in __recoverable
    logging.debug("response.headers: %s", response.headers)
AttributeError: 'SSLError' object has no attribute 'headers'
```
The issue is not the certificate failure, but the follow-on error.

**To Reproduce**

1. Have a Jira server that is set up with a self-signed certificate, which causes requests to raise an SSLError.
2. Execute the following Python code:
```
my_jira = jira.JIRA(server=MY_JIRA_BASE_URL, basic_auth=(MY_JIRA_EMAIL, MY_JIRA_TOKEN))
```
3. This fails with the stack trace shown below.

**Expected behavior**

The SSLError raised by the underlying requests package should be passed up to the user.

**Stack Trace**
The actual server DNS hostname has been replaced with `<jira_host>`.
```
WARNING:root:HTTPSConnectionPool(host='<jira_host>', port=8443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))) while doing GET https://<jira_host>':8443/rest/api/2/serverInfo [{'params': None, 'headers': {'User-Agent': 'python-requests/2.26.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='<jira_host>', port=8443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))] errno:None on GET https://<jira_host>:8443/rest/api/2/serverInfo
{'response': None, 'request': <PreparedRequest [GET]>}
{'response': None, 'request': <PreparedRequest [GET]>}
WARNING:root:Got recoverable error from GET https://<jira_host>:8443/rest/api/2/serverInfo, will retry [1/3] in 3.276003374985692s. Err: HTTPSConnectionPool(host='<jira_host>', port=8443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
Traceback (most recent call last):
  . . . (shortened)
  File ".../xyz.py", line NNN, in xyz
    my_jira = jira.JIRA(server=MY_JIRA_BASE_URL,
  File "/Users/maiera/virtualenvs/iaas39/lib/python3.9/site-packages/jira/client.py", line 506, in __init__
    si = self.server_info()
  File "/Users/maiera/virtualenvs/iaas39/lib/python3.9/site-packages/jira/client.py", line 2551, in server_info
    j = self._get_json("serverInfo")
  File "/Users/maiera/virtualenvs/iaas39/lib/python3.9/site-packages/jira/client.py", line 3139, in _get_json
    r = self._session.get(url, params=params)
  File "/Users/maiera/virtualenvs/iaas39/lib/python3.9/site-packages/jira/resilientsession.py", line 172, in get
    return self.__verb("GET", url, **kwargs)
  File "/Users/maiera/virtualenvs/iaas39/lib/python3.9/site-packages/jira/resilientsession.py", line 155, in __verb
    if self.__recoverable(
  File "/Users/maiera/virtualenvs/iaas39/lib/python3.9/site-packages/jira/resilientsession.py", line 120, in __recoverable
    logging.debug("response.headers: %s", response.headers)
AttributeError: 'SSLError' object has no attribute 'headers'
```

**Version Information**
Type of Jira instance:
- [ ] Jira Cloud (Hosted by Atlassian)
- [x] Jira Server or Data Center (Self-hosted)
Python Interpreter: Python 3.9.7
jira-python: 3.0.1
OS: macOS
IPython (Optional): N/A
Other Dependencies: requests 2.26.0, urllib3 1.26.6

**Additional context**
N/A

**Comment by andy-maier** [comment]
After looking at the code in the master branch, it turns out that this issue was addressed in PR #1023 (without mentioning much about it in the commit message). However, that fix is not in the latest released version.

Any chance to get a new version released?
