### ISSUE TITLE
Not able to create a project

### ISSUE THREAD

**Issue by hsekowski** [pycontribs/jira#1164]
**Describe the bug**
create_project function does not work as expected in this version
It worked in 2.0.0

**To Reproduce**
```
from jira import JIRA

jira = JIRA("http://localhost:8080/", basic_auth=("admin", "admin"))
project_key = 'PRJ'
project = jira.create_project(project_key)
```
1. Any additional steps or considerations that happen before or after.

**Expected behavior**

**Stack Trace**
```python
✗ python xyz/__init__.py
Traceback (most recent call last):
  File "xyz/__init__.py", line 35, in <module>
    project = jira.create_project(project_key)
  File "/Users/abc/Library/Caches/pypoetry/virtualenvs/issue-exploder-J4Ji3stn-py3.7/lib/python3.7/site-packages/jira/client.py", line 3775, in create_project
    r = self._session.post(url, data=json.dumps(payload))
  File "/Users/abc/Library/Caches/pypoetry/virtualenvs/issue-exploder-J4Ji3stn-py3.7/lib/python3.7/site-packages/jira/resilientsession.py", line 175, in post
    return self.__verb("POST", url, **kwargs)
  File "/Users/abc/Library/Caches/pypoetry/virtualenvs/issue-exploder-J4Ji3stn-py3.7/lib/python3.7/site-packages/jira/resilientsession.py", line 168, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/Users/abc/Library/Caches/pypoetry/virtualenvs/issue-exploder-J4Ji3stn-py3.7/lib/python3.7/site-packages/jira/resilientsession.py", line 54, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs
jira.exceptions.JIRAError: JiraError HTTP 400 url: http://localhost:8080/rest/api/2/project
	text: You must specify a valid project lead.
	
	response headers = {'X-AREQUESTID': '147x617x1', 'X-ASESSIONID': '1y0p5jh', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'sandbox', 'Strict-Transport-Security': 'max-age=31536000', 'X-Seraph-LoginReason': 'OK', 'X-AUSERNAME': 'admin', 'Cache-Control': 'no-cache, no-store, no-transform', 'Content-Encoding': 'gzip', 'Vary': 'User-Agent', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Mon, 04 Oct 2021 02:27:21 GMT', 'Connection': 'close'}
	response text = {"errorMessages":[],"errors":{"projectLead":"You must specify a valid project lead."}}
```

**Version Information**
Raised for self-hosted

**Comment by petermcd** [comment]
I have tested the proposed fix on a self hosted Jira and can confirm that it is now working for me, I was able to replicated the issue from master but when using the created branch im the linked pull request the functionality now works

![image](https://user-images.githubusercontent.com/148006/139746682-1dc61139-1042-4d4d-b008-f111eaa22ce3.png)

PRJ was me testing as I was taking a quick look into it myself, PRK was using the branch code unmodified.
