### ISSUE TITLE
oauth: ValueError: Only unicode objects are escapable

### ISSUE THREAD

**Issue by muffl0n** [pycontribs/jira#117]
I'm trying to do the "oauth dance" with jirashell. Unfortunately I get this error:
```
$ jirashell -s http://jira.example.com -u foo -p bar -od
Traceback (most recent call last):
  File "/tmp/jira_client/venv/bin/jirashell", line 11, in <module>
    sys.exit(main())
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/jira/jirashell.py", line 244, in main
    options['server'], oauth['consumer_key'], oauth['key_cert'], oauth['print_tokens'], options['verify'])
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/jira/jirashell.py", line 40, in oauth_dance
    server + '/plugins/servlet/oauth/request-token', verify=verify, auth=oauth)
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/requests/sessions.py", line 451, in request
    prep = self.prepare_request(req)
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/requests/sessions.py", line 382, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/requests/models.py", line 308, in prepare
    self.prepare_auth(auth, url)
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/requests/models.py", line 496, in prepare_auth
    r = auth(self)
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/requests_oauthlib/oauth1_auth.py", line 87, in __call__
    unicode(r.url), unicode(r.method), None, r.headers)
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/oauthlib/oauth1/rfc5849/__init__.py", line 313, in sign
    ('oauth_signature', self.get_oauth_signature(request)))
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/oauthlib/oauth1/rfc5849/__init__.py", line 128, in get_oauth_signature
    uri, headers, body = self._render(request)
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/oauthlib/oauth1/rfc5849/__init__.py", line 210, in _render
    request.oauth_params, request.headers, realm=realm)
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/oauthlib/oauth1/rfc5849/utils.py", line 31, in wrapper
    return target(params, *args, **kwargs)
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/oauthlib/oauth1/rfc5849/parameters.py", line 57, in prepare_headers
    escaped_value = utils.escape(value)
  File "/tmp/jira_client/venv/lib64/python3.4/site-packages/oauthlib/oauth1/rfc5849/utils.py", line 56, in escape
    'Got %s of type %s.' % (u, type(u)))
ValueError: Only unicode objects are escapable. Got None of type <class 'NoneType'>.
```

I'm not quite sure where to start debugging this. Is it an error in jirashell? Or in oauth?

Logging in with ``jirashell -s http://jira.example.com -u foo -p bar`` works like a charm.

**Comment by muffl0n** [comment]
I also tested it with Python 2.7.9 and got the same error.

**Comment by ssbarnea** [comment]
Please add a test (inside tests.py) that replicates the problem against our test instance. I will try to fix it if I have a test on it, otherwise I will keep this closed and consider oauth unsupported.

**Comment by ninowalker** [comment]
Ouch. Same problem. We had a forced upgrade, which now requires OAuth.

Here is a minimal test:

`$ jirashell -od -s https://livefyre.atlassian.net`

**Comment by eamonnfaherty** [comment]
+1
