### ISSUE TITLE
jira looses basic auth if redirected on first request

### ISSUE THREAD

**Issue by cybit** [pycontribs/jira#1196]
### Bug summary

If the first call to a jira server results in a permant redirect the next call will "forget" to include any basic auth header.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### Jira instance version

8.13.2

### jira-python version

3.0.1

### Python Interpreter version

3.9

### Which operating systems have you used?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Reproduction steps

```python
# Setup
The local Jira server instance is located behind a web server. Domains where changed and the old domain provides a 301 if called.

# Login using JIRA(basic_auth = ("username", "password"), options = {"server": "jira.old.domain", "verify" = "/etc/ssl/certs/ca-certificates.crt"}, validate = True)


## Low level view of exchange between jira client and servers.
### First call from jira client to server:

`b'GET /rest/auth/1/session HTTP/1.1\r\nHost: jira.old.domain.\r\nUser-Agent: python-requests/2.26.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/json,*.*;q=0.9\r\nConnection: keep-alive\r\nCache-Control: no-cache\r\nContent-Type: application/json\r\nX-Atlassian-Token: no-check\r\nAuthorization: Basic <REDACTED>\r\n\r\n'
`

### Answer from server: 301
`reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Date: Tue, 26 Oct 2021 16:02:19 GMT
header: Server: Apache/2.4.38 (Debian)
header: Location: https://jira.new.domain/rest/auth/1/session
`

### Next request from jira client to new server location

`b'GET /rest/auth/1/session HTTP/1.1\r\nHost: jira.new.domain\r\nUser-Agent: python-requests/2.26.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/json,*.*;q=0.9\r\nConnection: keep-alive\r\nCache-Control: no-cache\r\nX-Atlassian-Token: no-check\r\n\r\n'
`
### Answer from server:
`reply: 'HTTP/1.1 401 401\r\n'`

Notice the missing `Authorization: Basic <REDACTED>` header.
```

### Stack trace

```python
Traceback (most recent call last):
  File "/test/connections.py", line 65, in _login
    jira_session = JIRA(basic_auth = ("username", "password"), options = {"server": "jira.old.domain", "verify" = "/etc/ssl/certs/ca-certificates.crt"}, validate = True)
  File "/home/b/.virtualenvs/v/lib/python3.9/site-packages/jira/client.py", line 496, in __init__
    user = self.session()
  File "/home/b/.virtualenvs/v/lib/python3.9/site-packages/jira/client.py", line 2980, in session
    r = self._session.get(url)
  File "/home/b/.virtualenvs/v/lib/python3.9/site-packages/jira/resilientsession.py", line 172, in get
    return self.__verb("GET", url, **kwargs)
  File "/home/b/.virtualenvs/v/lib/python3.9/site-packages/jira/resilientsession.py", line 168, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/home/b/.virtualenvs/v/lib/python3.9/site-packages/jira/resilientsession.py", line 53, in raise_on_error
    raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 401 url: https://jira.new.domain/rest/auth/1/session
	text: You are not authenticated. Authentication required to perform this operation.
```

### Expected behaviour

jira client sees that the login request resulted in an 301 and re-sends the  request to the new URL including the Basic auth header.

**Comment by adehad** [comment]
Related reference: https://docs.python-requests.org/en/latest/api/#requests.Session.should_strip_auth
