### ISSUE TITLE
delete_user() fails with missing 'accountId' query parameter

### ISSUE THREAD

**Issue by kot0dama** [pycontribs/jira#1241]
### Bug summary

Calling delete_user(username=email@addre.ss) on a JIRA Cloud instance fails as it's missing accountId query parameter.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Cloud (Hosted by Atlassian)

### jira-python version

3.1.1

### Python Interpreter version

3.9.5

### Which operating systems have you used?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Reproduction steps

```python
# code is using classes but here's a more straightforward version
import jira
jira = JIRA(api_root, basic_auth=(api_user, api_token))
jira.delete_user(username="kotodama@example.com")
```

### Stack trace

```python
Traceback (most recent call last):
  File "./plugins/jiraapi.py", line 311, in <module>
    func(
  File "./plugins/jiraapi.py", line 272, in process_leaver
    self._jira.jira.delete_user(username="test.kotodama@canonical.com")
  File "/home/kotodama/.local/lib/python3.9/site-packages/jira/client.py", line 3657, in delete_user
    r = self._session.delete(url)
  File "/home/kotodama/.local/lib/python3.9/site-packages/jira/resilientsession.py", line 204, in delete
    return self.__verb("DELETE", str(url), **kwargs)
  File "/home/kotodama/.local/lib/python3.9/site-packages/jira/resilientsession.py", line 189, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/home/kotodama/.local/lib/python3.9/site-packages/jira/resilientsession.py", line 64, in raise_on_error
    raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 404 url: https://REDACTED.atlassian.net/rest/api/latest/user/?username=kotodama@example.com
        text: The 'accountId' query parameter needs to be provided

        response headers = REDACTED
        response text = {"errorMessages":["The 'accountId' query parameter needs to be provided"],"errors":{}}
```

### Expected behaviour

User should get deleted from JIRA instance.

**Comment by kot0dama** [comment]
Here's a workaround, fetch accountId and add it to the username as it's passed raw:
```python
class JiraAPIError(Exception):
    pass

class JiraAPIClient:
    [...]
    def user_info(self, email):
        """Fetch user info from JIRA."""
        # XXX This might need refresh when https://github.com/pycontribs/jira/pull/1109 is merged
        users = self.jira.search_users(None, 0, 5, True, False, email)
        if len(users) == 0:
            fmt = "Cannot find account matching email={}, were they just added ?"
            raise JiraAPIError(fmt.format(email))
        elif len(users) > 1:
            raise JiraAPIError("Multiple users found with email={}".format(email))
        user = users[0].raw
        # On JIRA Cloud there should be no email, but if present, check it.
        if (
            user.get("emailAddress")
            and user["emailAddress"] != ""
            and user["emailAddress"] != email
        ):
            msg = "Found user email ({}) do not match requested email ({})."
            raise JiraAPIError(msg.format(user["emailAddress"], email))
        return user

    def delete_user(self, email) -> bool:
        """Remove user from JIRA."""
        user_info = self.user_info(email)
        if "accountId" not in user_info:
            raise JiraAPIError("Unable to find user accountId.")
        # XXX This is a workaround until accountId is fully supported
        # XXX See: https://github.com/pycontribs/jira/pull/1109
        username = "{}&accountId={}".format(email, user_info["accountId"])
        return self.jira.delete_user(username=username)
```

**Comment by kot0dama** [comment]
I haven't had the time to check on how the plugin uses/finds accountId, but it seems both username and accountId are required for deleting a user. 

Maybe checking on my workaround will make it straightforward for you ?
If not, or if you need more information, please let me know.

Thank you!
