### ISSUE TITLE
token auth failed

### ISSUE THREAD

**Issue by liuqi605752176** [pycontribs/jira#1378]
### Bug summary

    jira = JIRA(options={'server' : "https://jira.n.xiaomi.com"}, token_auth='ODgyNjQ************Ogn5tR+k4YCP3***********')
    logger.info(jira)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### Jira instance version

v8.20.8

### jira-python version

main

### Python Interpreter version

3.9.0

### Which operating systems have you used?

- [ ] Linux
- [ ] macOS
- [X] Windows

### Reproduction steps

```python
# 1. Given a Jira client instance
jira: JIRA
# 2. When I call the function with argument x
jira.the_function(x)
# 3.
...
```

### Stack trace

```python
Traceback (most recent call last):
  File "E:\Code\Python\jira\venv\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\LQ\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\LQ\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\LQ\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Code\Python\jira\program\jira_search.py", line 278, in <module>
    jira = JIRA(options={'server' : "https://jira.n.xiaomi.com"}, token_auth='************************')
  File "E:\Code\Python\jira\venv\lib\site-packages\jira\client.py", line 578, in __init__
    si = self.server_info()
  File "E:\Code\Python\jira\venv\lib\site-packages\jira\client.py", line 2969, in server_info
    j = self._get_json("serverInfo")
  File "E:\Code\Python\jira\venv\lib\site-packages\jira\client.py", line 3635, in _get_json
    raise e
  File "E:\Code\Python\jira\venv\lib\site-packages\jira\client.py", line 3632, in _get_json
    r_json = json_loads(r)
  File "E:\Code\Python\jira\venv\lib\site-packages\jira\utils\__init__.py", line 74, in json_loads
    return r.json()
  File "E:\Code\Python\jira\venv\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="shortcut icon" href="https://cas.mioffice.cn/images/favicon_new.ico"/><meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"/><meta name="theme-color" content="#000000"/><meta http-equiv="X-UA-Compatible" content="IE=11"/><meta data-n-head="ssr" data-hid="description" name="description" content="相信美好，轻装上阵（Good times are always ahead. Travel light）"><link data-n-head="ssr" rel="apple-touch-icon" href="https://cas.mioffice.cn/images/favicon.ico" sizes="512x512"><link rel="icon" href="https://cas.mioffice.cn/images/favicon_new.ico" type="image/x-icon"/><title>内网统一认证 (Central Authentication Service)</title><script>window.onetrack=window.onetrack||function(){(onetrack.q=onetrack.q||[]).push(arguments)},onetrack("init","31000000113")</script><script async src="//ssl-cdn.static.browser.mi-img.com/mistat-data/onetrack/onetrack.js"></script><link href="/mcfe-cas-fe/static/static/css/1.773ae7ce.chunk.css" rel="stylesheet"><link href="/mcfe-cas-fe/static/static/css/main.7d7a6f10.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(i){function e(e){for(var t,r,n=e[0],o=e[1],a=e[2],c=0,u=[];c<n.length;c++)r=n[c],Object.prototype.hasOwnProperty.call(d,r)&&d[r]&&u.push(d[r][0]),d[r]=0;for(t in o)Object.prototype.hasOwnProperty.call(o,t)&&(i[t]=o[t]);for(h&&h(e);u.length;)u.shift()();return f.push.apply(f,a||[]),l()}function l(){for(var e,t=0;t<f.length;t++){for(var r=f[t],n=!0,o=1;o<r.length;o++){var a=r[o];0!==d[a]&&(n=!1)}n&&(f.splice(t--,1),e=p(p.s=r[0]))}return e}var r={},s={runtime:0},d={runtime:0},f=[];function p(e){if(r[e])return r[e].exports;var t=r[e]={i:e,l:!1,exports:{}};return i[e].call(t.exports,t,t.exports,p),t.l=!0,t.exports}p.e=function(f){var e=[];s[f]?e.push(s[f]):0!==s[f]&&{0:1,2:1,3:1,4:1,5:1}[f]&&e.push(s[f]=new Promise(function(e,n){for(var t="static/css/"+({}[f]||f)+"."+{0:"947d2409",2:"ac75ca3f",3:"cca3ddb1",4:"590fc431",5:"96e04a35",6:"31d6cfe0",7:"31d6cfe0"}[f]+".chunk.css",o=p.p+t,r=document.getElementsByTagName("link"),a=0;a<r.length;a++){var c=(i=r[a]).getAttribute("data-href")||i.getAttribute("href");if("stylesheet"===i.rel&&(c===t||c===o))return e()}var u=document.getElementsByTagName("style");for(a=0;a<u.length;a++){var i;if((c=(i=u[a]).getAttribute("data-href"))===t||c===o)return e()}var l=document.createElement("link");l.rel="stylesheet",l.type="text/css",l.onload=e,l.onerror=function(e){var t=e&&e.target&&e.target.src||o,r=new Error("Loading CSS chunk "+f+" failed.\n("+t+")");r.request=t,delete s[f],l.parentNode.removeChild(l),n(r)},l.href=o,document.getElementsByTagName("head")[0].appendChild(l)}).then(function(){s[f]=0}));var r=d[f];if(0!==r)if(r)e.push(r[2]);else{var t=new Promise(function(e,t){r=d[f]=[e,t]});e.push(r[2]=t);var n,o=document.createElement("script");o.charset="utf-8",o.timeout=120,p.nc&&o.setAttribute("nonce",p.nc),o.src=p.p+"static/js/"+({}[f]||f)+"."+{0:"05338ec8",2:"e5bf9c52",3:"308360f0",4:"127c0255",5:"9b33561a",6:"05c8f10d",7:"9cbca634"}[f]+".chunk.js";var a=new Error;n=function(e){o.onerror=o.onload=null,clearTimeout(c);var t=d[f];if(0!==t){if(t){var r=e&&("load"===e.type?"missing":e.type),n=e&&e.target&&e.target.src;a.message="Loading chunk "+f+" failed.\n("+r+": "+n+")",a.name="ChunkLoadError",a.type=r,a.request=n,t[1](a)}d[f]=void 0}};var c=setTimeout(function(){n({type:"timeout",target:o})},12e4);o.onerror=o.onload=n,document.head.appendChild(o)}return Promise.all(e)},p.m=i,p.c=r,p.d=function(e,t,r){p.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},p.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},p.t=function(t,e){if(1&e&&(t=p(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var r=Object.create(null);if(p.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var n in t)p.d(r,n,function(e){return t[e]}.bind(null,n));return r},p.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return p.d(t,"a",t),t},p.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},p.p="/mcfe-cas-fe/static/",p.oe=function(e){throw console.error(e),e};var t=window.webpackJsonp=window.webpackJsonp||[],n=t.push.bind(t);t.push=e,t=t.slice();for(var o=0;o<t.length;o++)e(t[o]);var h=n;l()}([])</script><script src="/mcfe-cas-fe/static/static/js/1.827d9b9a.chunk.js"></script><script src="/mcfe-cas-fe/static/static/js/main.95435cbf.chunk.js"></script></body></html>: 0
```

### Expected behaviour

login in the jira server by token auth successfully

**Comment by adehad** [comment]
Hi @liuqi605752176 sorry for the delay. From the last line of the stack trace I believe there is a separate (SSO?) authentication page being shown.

Do you know if the URL you using redirects to another URL? I believe we are encountering the same issue as #1340

**Comment by kwri-avongluck** [comment]
Same issue seen here.  Local user store + Personal Access Tokens.

Getting HTTP 400's back from Jira Datacenter
