### ISSUE TITLE
get_jira() raises "option values must be strings" in python 3.7

### ISSUE THREAD

**Issue by JorBratko** [pycontribs/jira#1479]
### Bug summary

get_jira() at config.py:63 initializes ConfigParser with defaults of None, but doesn't tell it to allow values of None

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### Jira instance version

doesn't matter

### jira-python version

2.0

### Python Interpreter version

3.7

### Which operating systems have you used?

- [ ] Linux
- [ ] macOS
- [X] Windows

### Reproduction steps

```python
# 1. Given a Jira client instance
jira: JIRA
# 2. When I call the function with argument x
jira.get_file(with any arguments)
# 3.
...
```

### Stack trace

```python
python-BaseException
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1216, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 753, in read_dict
    self.set(section, key, value)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
```

### Expected behaviour

get_jira() to get past initializing ConfigParser with defaults without raising an exception

**Comment by JorBratko** [comment]
Already fixed in jira 3.2.0
