### ISSUE TITLE
create_issue() and create_issues() methods giving error

### ISSUE THREAD

**Issue by anshuman-01-26** [pycontribs/jira#1590]
### Bug summary

I was using these methods to create JIRA tickets from a script and these were working fine till date but now these methods have started give wired error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Cloud (Hosted by Atlassian)

### jira-python version

3.4.1

### Python Interpreter version

3.8.0

### Which operating systems have you used?

- [ ] Linux
- [ ] macOS
- [X] Windows

### Reproduction steps

```python
1. make a connection using basic auth
connection = JIRA(server="server-name",basic_auth=(email,api-token))
2. define the issue fields
issue = {
    "project":{
        "key":"project-key"
    },
    "summary":"Name of bug",
    "description":"Description",
    "issuetype":{
        "name":"Bug"
    }

}
3. call the create_issue() function
connection.create_issue(fields=issue)
```

### Stack trace

```python
Traceback (most recent call last):
  File ".\test.py", line 16, in <module>
    connection.create_issue(fields=issue)
  File "C:\Users\AMO547\AppData\Local\Programs\Python\Python38\lib\site-packages\jira\client.py", line 1518, in create_issue
    r = self._session.post(url, data=json.dumps(data))
  File "C:\Users\AMO547\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\AMO547\AppData\Local\Programs\Python\Python38\lib\site-packages\jira\resilientsession.py", line 223, in request
    elif raise_on_error(response, **processed_kwargs):
  File "C:\Users\AMO547\AppData\Local\Programs\Python\Python38\lib\site-packages\jira\resilientsession.py", line 69, in raise_on_error
    raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://maersk-tools.atlassian.net/rest/api/2/issue

        response headers = {'Date': 'Tue, 17 Jan 2023 05:38:09 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Server': 'AtlassianEdge', 'Timing-Allow-Origin': '*', 'X-Arequestid': '8f81abe4a1d868752f172959b2dc69df', 'X-Ratelimit-Nearlimit': 'false', 'X-Aaccountid': '63039e7055513d8d731006ef', 'Cache-Control': 'no-cache, no-store, no-transform', 'Expect-Ct': 'report-uri="https://web-security-reports.services.atlassian.com/expect-ct-report/atlassian-proxy", max-age=86400', 'X-Content-Type-Options': 'nosniff', 'X-Xss-Protection': '1; mode=block', 'Atl-Traceid': '977cc6774301b69b', 'Report-To': '{"endpoints": [{"url": "https://dz8aopenkvv6s.cloudfront.net"}], "group": "endpoint-1", "include_subdomains": true, "max_age": 600}', 'Nel': '{"failure_fraction": 0.001, "include_subdomains": true, "max_age": 600, "report_to": "endpoint-1"}', 'Strict-Transport-Security': 'max-age=63072000; 
includeSubDomains; preload', 'Transfer-Encoding': 'chunked'}
        response text = {"errorMessages":[],"errors":{"components":"Components is required."}}
```

### Expected behaviour

i wanted the issue to be created

**Comment by princenyeche** [comment]
The error mentions component is required, so add the component field to the create payload you're sending.

**Comment by studioj** [comment]
indeed @princenyeche I'll close the issue
