### ISSUE TITLE
JIRA.boards() broken maxResults kwarg and fails to retrieve board by ID

### ISSUE THREAD

**Issue by RAYemelyanova** [pycontribs/jira#1618]
### Bug summary

I am using the jira library to try and create tickets/issues on a Kankan board. I have been able to authenticate through the library, however am stuck at trying to retrieve my Kankan board. According to the [API](https://jira.readthedocs.io/api.html#jira.client.JIRA.boards), I can use the keyword `projectKeyOrID` to specify the ID of my board. I know the ID from the URL. However when I enter this number, I get an error telling me that no project can be found with that key.

If I instead decide to get all the boards available by setting `maxResults` to 10000, I still only get 50 results back. I have to specify the 'startAt' keyword and increment it by 50 to find my board, in alphabetical order. Once I do find it, I can confirm that the ID of the board is exactly what I expect, which makes me believe that there may be something wrong with these calls. Or, perhaps I am missing something else.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### Jira instance version

8.20.12

### jira-python version

3.4.1

### Python Interpreter version

3.11.2

### Which operating systems have you used?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Reproduction steps

```python
# 1. Given a Jira client instance
jira: JIRA
# 2. When I call the function with argument x
jira.the_function(x)
# 3.
...
>>> from jira import JIRA

>>> jira = JIRA(
...    server="{$INTRANET_JIRA_SERVER}",
...    token_auth="${JIRA_PERSONAL_ACCESS_TOKEN}",
... )

>>> boards= jira.boards(maxResults=1000)
>>> len(boards) 
50 #should be 1000, as there are more than 1000 boards in my organisation.

>>> boards = jira.boards(startAt=90, maxResults=10000) #this seems to move the boards along alphabetically, e.g. boards[50] seems to have the first letter as a 'B' with default kwargs for boards() call.
>>> board[3] 
<JIRA Board: name='DAQ Sprints', id=1773>

>>> jira.boards(projectKeyOrID=1773)
```

### Stack trace

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv/lib/python3.11/site-packages/jira/client.py", line 119, in wrapper
    result = func(*arg_list, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/jira/client.py", line 4627, in boards
    return self._fetch_pages(
           ^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/jira/client.py", line 729, in _fetch_pages
    resource = self._get_json(request_path, params=page_params, base=base)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/jira/client.py", line 3764, in _get_json
    r = self._session.get(url, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.11/site-packages/jira/resilientsession.py", line 223, in request
    elif raise_on_error(response, **processed_kwargs):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...venv/lib/python3.11/site-packages/jira/resilientsession.py", line 69, in raise_on_error
    raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://${INTRANET_JIRA_SERVER}/rest/agile/1.0/board?projectKeyOrId=1773&maxResults=50
        text: No project could be found with id '1773'.

        response headers = {'Date': 'Thu, 02 Mar 2023 17:13:09 GMT', 'Server': 'Apache/2.4.37 (Red Hat Enterprise Linux) OpenSSL/1.1.1k', 'X-AREQUESTID': '1033x740504x1', 'X-ANODEID': 'node1', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'sandbox', 'Strict-Transport-Security': 'max-age=31536000', 'X-Seraph-LoginReason': 'OK', 'X-ASESSIONID': '1paxgvx', 'X-AUSERNAME': 'ton99817', 'Cache-Control': 'no-cache, no-store, no-transform', 'Content-Type': 'application/json;charset=UTF-8', 'Set-Cookie': 'JSESSIONID=0A386E238A28669C97956B349CD0A913; Path=/; Secure; HttpOnly, atlassian.xsrf.token=A614-HVB0-75LU-P8EK_14c383d240cad535b015fabd5f7f87422db83025_lin; Path=/; Secure; SameSite=None', 'Connection': 'close', 'Transfer-Encoding': 'chunked'}
        response text = {"errorMessages":["No project could be found with id '1773'."],"errors":{}}
```

### Expected behaviour

I expect it the jira.boards() command to retrieve the correct board with the correct id.

I'm not sure what's going on. Could this be a problem with the URL that this library is trying to contact, or a configuration my Jira admin might need to change, or anything else?

Thanks

**Comment by alanmxll** [comment]
This already happened to me. However, with another language.

This seems to me to be an API issue, not a package issue. I tried to replicate your error and it really happens, if you made the request directly through Postman, the problem also occurs.

```json
{
    "errorMessages": [
        "No project could be found with id '359'."
    ],
    "errors": {}
}
```

You have the option to use the route of searching a single board by id ([This url](https://docs.atlassian.com/jira-software/REST/9.5.0/#agile/1.0/board-getBoard)) or use recursion to get all the boards from your Jira Server and then applying a filter on the board you want.

Something like that:

``` python
def get_all_boards(start_at=0, partial_boards=[]):
    all_boards = [*partial_boards]
    current_boards = jira_server.boards(startAt=start_at)
    all_boards = [*partial_boards, *current_boards]
    total = current_boards.total

    if len(all_boards) < total:
        return get_boards(start_at=len(all_boards), partial_boards=all_boards)

    return all_boards
```

Maybe not the best way to approach the situation, but it worked for me. 👍

**Comment by cpdivers** [comment]
I have some what the same issue. I did circumvant the 50 board limit issue by using paging. 

I still have a major issue as I cannot find a fast way to query only 1 board with 

boards = jira.boards(projectKeyOrID=project_key)

None of the project_key value I use works !!! From my point of view, this function is broken.
Another idea would be to create a new function such as jira.board (singular) just to query 1 board

@ here is the function to fetch all board
`def fetch_all_boards(jira): 
    """
    Fetch all boards in JIRA, handling pagination.
    
    :param jira: JIRA client object
    :return: List of all boards
    """
    start_at = 0
    max_results = 50
    all_boards = []

    while True:
        boards = jira.boards(startAt=start_at, maxResults=max_results)
        if not boards:
            break
        all_boards.extend(boards)
        start_at += len(boards)

    return all_boards`
