### ISSUE TITLE
Import requests and urllib3 has conflict

### ISSUE THREAD

**Issue by Extpilot** [pycontribs/jira#1655]
### Bug summary

According to requests project: https://github.com/psf/requests/issues/6443
There is a conflict with urllib3 2.0.2 and requests 1.30.0
This is causing import errors downstream when importing the Jira module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### jira-python version

3.4.1,3.5.0

### Python Interpreter version

3.9.6

### Which operating systems have you used?

- [X] Linux
- [X] macOS
- [ ] Windows

### Reproduction steps

```python
# 1. Install latest urllib3 - pip install urllib3==2.0.2
# 2. Install latest requests - pip install requests==2.30.0
# 3. Install latest jira - pip install jira==3.5.0
# 4. Run python - python
# 5. Import jira - import jira
```

### Stack trace

```python
Python 3.9.6 (default, Oct 18 2022, 12:41:40)
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jira
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<>/.venv/lib/python3.9/site-packages/jira/__init__.py", line 9, in <module>
    from jira.client import (
  File "<>/.venv/lib/python3.9/site-packages/jira/client.py", line 46, in <module>
    import requests
  File "<>/.venv/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "<>/.venv/lib/python3.9/site-packages/urllib3/__init__.py", line 38, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https://github.com/urllib3/urllib3/issues/2168
```

### Expected behaviour

Successfully import and utilize jira module

### Additional Context

Happening in other environments such-as linux running a Jenkins pipeline to build a project that uses Jira module

**Comment by Extpilot** [comment]
Note: Force downgrade requests to 2.29.0 allows jira to import correctly.
```
(.venv) <>% pip install --force-reinstall -v requests==2.29.0
...
(.venv) <> % python
Python 3.9.6 (default, Oct 18 2022, 12:41:40)
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jira
>>>

**Comment by studioj** [comment]
@Extpilot thank you for reporting

Its a problem of dependencies, nothing much we can do. I'll leave the ticket open until its resolved in the requests package. (as mentioned above https://github.com/psf/requests/issues/6443)
This way people encountering the same problem will be able to find a solution.
