### ISSUE TITLE
Regression in add_attachment(), fails on bytes object

### ISSUE THREAD

**Issue by bvle** [pycontribs/jira#1735]
### Bug summary

When a `bytes` object is passed as the attachment argument to `add_attachment()` it raises an AttributeError. This was not the case before #1366 (first seen in v3.3.0).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### Jira instance version

v8.9.0#809000-sha1:4ceb90a

### jira-python version

3.5.2

### Python Interpreter version

Python 3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0] on linux

### Which operating systems have you used?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Reproduction steps

```python
from jira import JIRA

jira = JIRA(basic_auth=("admin", "admin"))
jira.add_attachment(
    issue="QQ-1",
    attachment=b"example content",
    filename="example.txt",
)
print("ok")
```

### Stack trace

```python
Traceback (most recent call last):
  File "/home/bvl/dev/scratch/./test_regression_1366.py", line 4, in <module>
    jira.add_attachment(
  File "/home/bvl/dev/scratch/jirra/venv/lib/python3.11/site-packages/jira/client.py", line 123, in wrapper
    result = func(*arg_list, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bvl/dev/scratch/jirra/venv/lib/python3.11/site-packages/jira/client.py", line 1032, in add_attachment
    encoded_data, request_headers = generate_multipartencoded_request_args()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bvl/dev/scratch/jirra/venv/lib/python3.11/site-packages/jira/client.py", line 1009, in generate_multipartencoded_request_args
    attachment_io.seek(0)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'seek'
```
```


### Expected behaviour

The attachment will be present on the issue, with the given content and filename.
```bash
$ python ./test_regression_1366.py
ok
```

**Comment by Mukller** [comment]
Root cause: `add_attachment()` calls `attachment_io.seek(0)` inside `generate_multipartencoded_request_args()`. When a `bytes` object is passed as `attachment`, `attachment_io` is set to the `bytes` object directly (the `else` branch), and `bytes.seek` does not exist:

```python
# client.py — add_attachment()
close_attachment = False
if isinstance(attachment, str):
    attachment_io = open(attachment, 'rb')
    close_attachment = True
else:
    attachment_io = attachment   # bytes lands here
    ...

# later:
def generate_multipartencoded_request_args():
    attachment_io.seek(0)        # AttributeError: bytes has no seek()
    ...
```

**Fix:** add an explicit `bytes` branch that wraps the content in `io.BytesIO`, which supports `.seek(0)` and is accepted by `MultipartEncoder` just like `BufferedReader`:

```diff
+from io import BufferedReader, BytesIO

 def add_attachment(self, issue, attachment: str | bytes | BufferedReader, filename=None):
     close_attachment = False
     if isinstance(attachment, str):
         attachment_io = open(attachment, 'rb')
         close_attachment = True
+    elif isinstance(attachment, bytes):
+        attachment_io = BytesIO(attachment)
+        close_attachment = True
     else:
         attachment_io = attachment
         ...
```

Note: when passing `bytes`, a `filename` argument is required because `BytesIO` has no `.name` attribute.

I have a PR ready.
