### ISSUE TITLE
issue.update data format trouble

### ISSUE THREAD

**Issue by k0ste** [pycontribs/jira#178]
Hi.

Error on code or documentation. See the example. The correct format is (its work :):

``` python
    issue.update(fields={"customfield_12601":["Cactus"]})
```

Script:

``` python
#!/usr/bin/python2
# -*- coding: utf-8 -*-

import os
from optparse import OptionParser

def updater(key, component, sup):
    issue = jira.issue(key)
    '''python jira documentation'''
    issue.update(fields={"customfield_12601":"Cactus"})
    '''JIRA API documentation'''
    issue.update(fields={ "customfield_12601": [{"value":"Cactus"}] })

def main():
    '''Check jira module installed or not'''
    try:
        from jira import JIRA,JIRAError
    except ImportError:
        print 'python-jira not found, please install it'
        raise SystemExit

    parser = OptionParser(usage='%prog -s http://localhost/jria -u admin -p admin', version='%prog 0.1')
    parser.add_option('-s', '--server', type='string', dest='jira_server', help='JIRA instance')
    parser.add_option('-u', '--username', type='string', dest='jira_username', default='admin', help='Username of JIRA account for auth basic [default: %default]')
    parser.add_option('-p', '--password', type='string', dest='jira_password', default='admin', help='Password of JIRA account for auth basic [default: %default]')
    (options, args) = parser.parse_args()

    if not options.jira_server or not options.jira_username or not options.jira_password:
        parser.print_help()
        raise SystemExit

    global jira
    global JIRAError
    try:
        jira = JIRA(server=options.jira_server, basic_auth=(options.jira_username, options.jira_password))
    except JIRAError:
        print 'Can\'t connet to JIRA on: \'%s\' with username \'%s\' and password \'%s\'' % (options.jira_server, options.jira_username, options.jira_password)
        raise SystemExit

    key = 'SUPPLY-6259'
    comp = 'CACTUS'
    sup = 'Cactus'
    updater(key, comp, sup)

if __name__ == "__main__":
  main()
```

**Traceback (python jira documentation):**

``` python
Traceback (most recent call last):
  File "./mosh.py", line 47, in <module>
    main()
  File "./mosh.py", line 44, in main
    updater(key, comp, sup)
  File "./mosh.py", line 9, in updater
    issue.update(fields={"customfield_12601":"Cactus"})
  File "/usr/lib/python2.7/site-packages/jira/resources.py", line 412, in update
    super(Issue, self).update(async=async, jira=jira, fields=data)
  File "/usr/lib/python2.7/site-packages/jira/resources.py", line 178, in update
    self.self, data=data)
  File "/usr/lib/python2.7/site-packages/jira/resilientsession.py", line 136, in put
    return self.__verb('PUT', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/jira/resilientsession.py", line 126, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/usr/lib/python2.7/site-packages/jira/resilientsession.py", line 45, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError: JiraError HTTP 400
    text: data was not an array
```

**Tracerback (JIRA API documentation)**

``` python
Traceback (most recent call last):
  File "./mosh.py", line 47, in <module>
    main()
  File "./mosh.py", line 44, in main
    updater(key, comp, sup)
  File "./mosh.py", line 10, in updater
    issue.update(fields={ "customfield_12601": [{"value":"Cactus"}] })
  File "/usr/lib/python2.7/site-packages/jira/resources.py", line 412, in update
    super(Issue, self).update(async=async, jira=jira, fields=data)
  File "/usr/lib/python2.7/site-packages/jira/resources.py", line 178, in update
    self.self, data=data)
  File "/usr/lib/python2.7/site-packages/jira/resilientsession.py", line 136, in put
    return self.__verb('PUT', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/jira/resilientsession.py", line 126, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/usr/lib/python2.7/site-packages/jira/resilientsession.py", line 45, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError: JiraError HTTP 400
    text: string expected at index 0
```
##

**Comment by hdost** [comment]
This basically just needs to be updated so the documentation says
```
 issue.update(fields={"customfield_12601":["Cactus"]})
```

**Comment by mhienle** [comment]
`customfield_12601` can no longer be found in the repo, so I guess this issue can be closed?
