### ISSUE TITLE
Calling add_user() on Jira Cloud instances fails with: You must specify the products that user can access.

### ISSUE THREAD

**Issue by kot0dama** [pycontribs/jira#1869]
### Bug summary

Calling add_user() on Jira Cloud instances fails with this error: `You must specify the products that user can access.`

This seems to be a new requirement on Jira Cloud instances from about 2 weeks ago.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Cloud (Hosted by Atlassian)

### jira-python version

3.5.2-1

### Python Interpreter version

3.12.3

### Which operating systems have you used?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Reproduction steps

```python
# 1. Given a Jira client instance
jira: JIRA
# 2. When I call the add_user with either of these arguments
jira.add_user(username="REDACTED", email="REDACTED", fullname="REDACTED", notify=True, application_keys=["jira-software"])
jira.add_user(username="REDACTED", email="REDACTED", fullname="REDACTED", notify=True)
```

### Stack trace

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/jira/client.py", line 4630, in add_user
    raise e
  File "/usr/lib/python3/dist-packages/jira/client.py", line 4620, in add_user
    self._session.post(url, data=payload)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jira/resilientsession.py", line 246, in request
    elif raise_on_error(response, **processed_kwargs):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jira/resilientsession.py", line 71, in raise_on_error
    raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://REDACTED/rest/api/latest/user
        text: You must specify the products that user can access.

        response headers = REDACTED
        response text = {"errorMessages":["You must specify the products that user can access."],"errors":{}}
```

### Expected behaviour

`add_user()` method shall comply with Jira Cloud requirements, and send a product list.

Calling a modified add_user() method, adding products like this fixes it:
https://github.com/pycontribs/jira/blob/main/jira/client.py#L5126
```diff
         if notify:
             x["notification"] = "True"
+       if products is not None:
+           x["products"] = products
         if application_keys is not None:
             x["applicationKeys"] = application_keys
```

Tested and confirmed working with `products = ["jira-software"]`

Thank you,
Loïc

**Comment by zousu** [comment]
When can this version be updated？

**Comment by princenyeche** [comment]
In the payload, you should specify a product or use an empty list if you just want to create the user without being added to any product
```python
{
"emailAddress": "user@example.com",
"products": []
}
```
This update was added in May about [products field now mandatory in the Create User API](https://developer.atlassian.com/cloud/jira/platform/changelog/#CHANGE-1636)

**Comment by kot0dama** [comment]
Noted, thanks, feel free to close this issue since there is a workaround.
