### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lechat** [pycontribs/jira#216]
Hi,

When I try to `python setup.py develop` it fails with

```
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    __version__ = __import__(NAME).get_version()
  File "jira/__init__.py", line 3, in <module>
    from jira.utils.version import get_version
  File "jira/utils/__init__.py", line 5, in <module>
    from jira.resilientsession import raise_on_error
  File "jira/resilientsession.py", line 3, in <module>
    from requests import Session
ImportError: No module named requests
```

This is because `jira/__init__.py` tries to import `get_version` from `utils/version.py`, but `utils/__init__.py` has dependency on `requests`... 

I can try fixing that, but I am a bit scared that this would be a big change, ecpecially knowing that currently unit tests are broken.

**Comment by lechat** [comment]
Fixed in PR #227
