### ISSUE TITLE
make error messages helpful

### ISSUE THREAD

**Issue by ryantuck** [pycontribs/jira#243]
attempting to connect to pull from jira, and I get this stack trace, which doesn't at all tell me what's going on. 

```
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    pull_and_load(0,0)
  File "main.py", line 25, in pull_and_load
    jira = JIRA(options, basic_auth=('my_user', 'my_passwd'))
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/jira/client.py", line 303, in __init__
    si = self.server_info()
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/jira/client.py", line 1755, in server_info
    j = self._get_json('serverInfo')
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/jira/client.py", line 2165, in _get_json
    r = self._session.get(url, params=params)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/jira/resilientsession.py", line 149, in get
    return self.__verb('GET', url, **kwargs)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/jira/resilientsession.py", line 145, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/jira/resilientsession.py", line 55, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError
```

Error messaging should be improved to describe what error is actually occurring.

**Comment by candy901122** [comment]
I am facing the same issue.

**Comment by ssbarnea** [comment]
Do you realise that you posted only an exception without any information on how to reproduce it? If you provide more info someone may be able to make PR to address it.

But in general I do agree that error messages should be nicer but this is not as easy as one would imagine because in 99% of the cases we only identify that we received a unexpected response from JIRA, and in many cases this is not a human readable one.

**Comment by hdost** [comment]
@ryantuck For this particular issue it looks like you need to specify `JIRA(options=options, basic_auth=('user','pass'))` since the first argument should be server. The enhancement in this case could be just verifying server is a string an not a dictionary.
