### ISSUE TITLE
Unable to authenticate with BasicAuth

### ISSUE THREAD

**Issue by ashish-padakannaya** [pycontribs/jira#244]
I'm using the python-jira module to plug into our jira instance online and basic authentication isn't working. i cannot use OAuth as i consumer tokens for that i don't have admin privileges. I'm guessing i need to use my certificates to authenticate but it seems unnecessary as everything works perfectly fine in postman without using my certs.

PFA my python script and the error it throws when i try to run it. please advice

Python script
`from jira import JIRA`
`jira_options = { "server":"https://gsd-api.mycompany.com:8443/jira/", "verify":False }`
`jira = JIRA(options=jira_options, basic_auth=('myusername', 'mypassword'))`

Error

```
/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cors is deprecated, use flask_cors instead.
  .format(x=modname), ExtDeprecationWarning
/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "flaskApp.py", line 21, in <module>
    jira = JIRA(options=jira_options, basic_auth=(credentials.username, credentials.password))
  File "/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/jira/client.py", line 303, in __init__
    si = self.server_info()
  File "/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/jira/client.py", line 1755, in server_info
    j = self._get_json('serverInfo')
  File "/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/jira/client.py", line 2165, in _get_json
    r = self._session.get(url, params=params)
  File "/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/jira/resilientsession.py", line 149, in get
    return self.__verb('GET', url, **kwargs)
  File "/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/jira/resilientsession.py", line 123, in __verb
    response = method(url, **kwargs)
  File "/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/Users/mpadakan/Library/Python/2.7/lib/python/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 194, in recv
    data = self.connection.recv(*args, **kwargs)
OpenSSL.SSL.Error: [('SSL routines', 'SSL3_READ_BYTES', 'sslv3 alert handshake failure'), ('SSL routines', 'SSL3_READ_BYTES', 'ssl handshake failure')]
```

PS: is there any way to include my cert file in the authentication part?

**Comment by lechat** [comment]
This question is better suited for Requests library that is used behind the scenes.

**Comment by ssbarnea** [comment]
Sorry but this is clearly not in our garden, but I think that you will find this as a workaround https://github.com/kennethreitz/requests/issues/2899#issuecomment-261810447
