### ISSUE TITLE
Jirashell, anything with oauth requires jwt.algorithms

### ISSUE THREAD

**Issue by rsvancara** [pycontribs/jira#247]
I have tried:  python 3.5, python 2.7, various versions of anaconda python.  All I want to do is generate an access token for the jira oauth dance....but alas, nothing is easy it seams and for a such a high profile project I would not expect this to be a problem.  However everytime I run 

jirashell -od -k ~/JIRA/jira.pub -ck jlf -pt -u someuser -P -s http://somehost.atlassian.net

I see the error:

```
1 Traceback (most recent call last):
  2   File "/Users/someuser/anaconda/bin/jirashell", line 11, in <module>
  3     sys.exit(main())
  4   File "/Users/someuser/anaconda/lib/python3.5/site-packages/jira/jirashell.py", line 244, in main
  5     options['server'], oauth['consumer_key'], oauth['key_cert'], oauth['print_tokens'], options['verify'])
  6   File "/Users/someuser/anaconda/lib/python3.5/site-packages/jira/jirashell.py", line 39, in oauth_dance
  7     server + '/plugins/servlet/oauth/request-token', verify=verify, auth=oauth)
  8   File "/Users/someuser/anaconda/lib/python3.5/site-packages/requests/api.py", line 111, in post
  9     return request('post', url, data=data, json=json, **kwargs)
 10   File "/Users/someuser/anaconda/lib/python3.5/site-packages/requests/api.py", line 57, in request
 11     return session.request(method=method, url=url, **kwargs)
 12   File "/Users/someuser/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 461, in request
 13     prep = self.prepare_request(req)
 14   File "/Users/someuser/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 394, in prepare_request
 15     hooks=merge_hooks(request.hooks, self.hooks),
 16   File "/Users/someuser/anaconda/lib/python3.5/site-packages/requests/models.py", line 299, in prepare
 17     self.prepare_auth(auth, url)
 18   File "/Users/someuser/anaconda/lib/python3.5/site-packages/requests/models.py", line 494, in prepare_auth
 19     r = auth(self)
 20   File "/Users/someuser/anaconda/lib/python3.5/site-packages/requests_oauthlib/oauth1_auth.py", line 88, in __call__
 21     unicode(r.url), unicode(r.method), None, r.headers)
 22   File "/Users/someuser/anaconda/lib/python3.5/site-packages/oauthlib/oauth1/rfc5849/__init__.py", line 313, in sign
 23     ('oauth_signature', self.get_oauth_signature(request)))
 24   File "/Users/someuser/anaconda/lib/python3.5/site-packages/oauthlib/oauth1/rfc5849/__init__.py", line 150, in get_oauth_signature
 25     sig = self.SIGNATURE_METHODS[self.signature_method](base_string, self)
 26   File "/Users/someuser/anaconda/lib/python3.5/site-packages/oauthlib/oauth1/rfc5849/signature.py", line 505, in sign_rsa_sha1_with_client
 27     return sign_rsa_sha1(base_string, client.rsa_key)
 28   File "/Users/someuser/anaconda/lib/python3.5/site-packages/oauthlib/oauth1/rfc5849/signature.py", line 496, in sign_rsa_sha1
 29     alg = _jwt_rs1_signing_algorithm()
 30   File "/Users/someuser/anaconda/lib/python3.5/site-packages/oauthlib/oauth1/rfc5849/signature.py", line 473, in _jwt_rs1_signing_algorithm
 31     import jwt.algorithms as jwtalgo
 32 ImportError: No module named 'jwt.algorithms'
```

Looks like jwt no longer includes algorithms???  Can you recommend a version of JWT that does??

**Comment by GertBurger** [comment]
Did you eventually figure this out?

**Comment by xiaket** [comment]
I bumped into this one for python 2.7 as well.

**Comment by hdost** [comment]
JWT is part of the optional packages that we include See: https://github.com/pycontribs/jira/blob/master/setup.cfg

**Comment by tjb7** [comment]
Still running into this issue, the fix pip install -U pyjwt worked for me. The first time I installed jwt I mistakenly wrote pip install jwt, maybe this was the problem.
