### ISSUE TITLE
HTTP 500 url when using Basic Auth

### ISSUE THREAD

**Issue by bigred134** [pycontribs/jira#283]
Hi All,

I am having some troubles with the jira module with Python 3.4.

I am authing with our jira cloud with the following:

`JIRA_USER="user"
JIRA_PASSWD="*************"
JIRA_SERVER="https://******.atlassian.net"
jira_options = {'server': JIRA_SERVER}
jira = JIRA(jira_options, basic_auth=(JIRA_USER, JIRA_PASSWD))`

When doing this I get the following error:
`Traceback (most recent call last):
  File "./auto.py", line 49, in <module>
    jira_rw = JIRA(jira_options, basic_auth=(JIRA_USER_RW, JIRA_PASSWD_RW))
  File "/usr/local/lib/python3.4/dist-packages/jira/client.py", line 303, in __init__
    si = self.server_info()
  File "/usr/local/lib/python3.4/dist-packages/jira/client.py", line 1755, in server_info
    j = self._get_json('serverInfo')
  File "/usr/local/lib/python3.4/dist-packages/jira/client.py", line 2165, in _get_json
    r = self._session.get(url, params=params)
  File "/usr/local/lib/python3.4/dist-packages/jira/resilientsession.py", line 149, in get
    return self.__verb('GET', url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jira/resilientsession.py", line 145, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jira/resilientsession.py", line 55, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError: JiraError HTTP 500 url: https://********.atlassian.net/rest/api/2/serverInfo details: /tmp/jiraerror-rsj9jj_t.tmp`

The contents of the tmp file is error page from atlassian including the stack trace:
[jira Error.txt](https://github.com/pycontribs/jira/files/588178/jira.Error.txt)

This appears to line up with a bug on Jira cloud:
https://jira.atlassian.com/browse/JRA-63105

However I have raised a support ticket to address the exact problem we are experiencing as our server has been patched and the reply from support has been to not use authentication on the URLs we are getting the 500 error from.

So using jira_test = JIRA(jira_options) returns no errors.

I understand this is probably a Atlassian problems but they are doing everything they can to say that everything was fixed in their patch and any fix will take some time.

Does anyone have any workarounds or suggestions that may get me back up and running?

**Comment by bigred134** [comment]
Not sure how but the problem is no longer :)
