### ISSUE TITLE
Cannot create new issue

### ISSUE THREAD

**Issue by aurelx** [pycontribs/jira#29]
>>> new_issue_dict = {
...     'project': {'key': 'SBOP'},
...     'summary': 'FixStorage Error on test01 / au03test01',
...     'description': 'test 1 2 3 4 5',
...     'issuetype': {'name': 'Inquiry'},
...     'priority': {'name': 'Critical'},
...     'components': {'name': 'Troubleshooting'},
... }
>>> new_issue = jira.create_issue(fields=new_issue_dict)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/timyip/pythonenv/lib/python3.3/site-packages/jira/client.py", line 694, in create_issue
    r = self._session.post(url, data=json.dumps(data))
  File "/home/timyip/pythonenv/lib/python3.3/site-packages/jira/resilientsession.py", line 81, in post
    return self.__verb('POST', url, **kwargs)
  File "/home/timyip/pythonenv/lib/python3.3/site-packages/jira/resilientsession.py", line 74, in __verb
    raise_on_error(r, verb=verb, **kwargs)
  File "/home/timyip/pythonenv/lib/python3.3/site-packages/jira/utils.py", line 120, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.utils.JIRAError: JiraError HTTP 400
	text: data was not an array
	url: https://jira.dev.smbc.nasdaqomx.com/jira/rest/api/2/issue

>>> new_issue = jira.create_issue(project='SBOP', summary='FixStorage Error on test01 / au03test01', description='test 1 2 3', issuetype={'name': 'Inquiry'}, priority={'name': 'Critical'}, components={'name': 'Storage'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/timyip/pythonenv/lib/python3.3/site-packages/jira/client.py", line 694, in create_issue
    r = self._session.post(url, data=json.dumps(data))
  File "/home/timyip/pythonenv/lib/python3.3/site-packages/jira/resilientsession.py", line 81, in post
    return self.__verb('POST', url, **kwargs)
  File "/home/timyip/pythonenv/lib/python3.3/site-packages/jira/resilientsession.py", line 74, in __verb
    raise_on_error(r, verb=verb, **kwargs)
  File "/home/timyip/pythonenv/lib/python3.3/site-packages/jira/utils.py", line 120, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.utils.JIRAError: JiraError HTTP 400
	text: data was not an array
	url: https://jira.dev.smbc.nasdaqomx.com/jira/rest/api/2/issue

Any idea?
Using jira 0.39

**Comment by aurelx** [comment]
Nevermind, I figured it out. Putting square brackets around the components solved it.

>>> new_issue = jira.create_issue(project='SBOP', summary='FixStorage Error on test01 / au03test01', description='test 1 2 3', issuetype={'name': 'Inquiry'}, priority={'name': 'Critical'}, components=[{'name': 'Storage'}])
>>>

**Comment by hezhiming** [comment]
I meet the same issue, and all my args is correct, but still failed

My args
```
# create an feature
issue_dict = {
    'project': {'id': 10608},
    'duedate': '2016-11-11',
    'issuetype': {'id': '2'},  # new feature
    # Priorty Level
    'customfield_10206': {'id': '10523'},
    # fix versions
    'fixVersions': [{'id': '12602'}],  #
    # components
    'components': [{'id': '11060'}],
    # summary
    'summary': '这个feature是通过jira-rest-api创建的(Python)',
    # description
    'description': '这个feature是通过jira-rest-api创建的(Python)',
    # attachment

    # assignee
    'assignee': {'name': 'he.zhiming'},
    # CC
    'customfield_10207': [{'name': 'he.zhiming'}],
    # SourceIndustries  行业来源
    # 'customfield_11200': '',  #
    # SourceArea        需求来源区域
    # 'customfield_11201': '',  #
    # Customer
    'customfield_11204': ['bbb']
}
new_issue = jira.create_issue(fields=issue_dict)
```

And the error
```
Traceback (most recent call last):
  File "C:/ddisk/work/jira-rest-api/ab_jira_rest/main.py", line 46, in <module>
    new_issue = jira.create_issue(fields=issue_dict)
  File "C:\Anaconda2\lib\site-packages\jira\client.py", line 897, in create_issue
    r = self._session.post(url, data=json.dumps(data))
  File "C:\Anaconda2\lib\site-packages\jira\resilientsession.py", line 152, in post
    return self.__verb('POST', url, **kwargs)
  File "C:\Anaconda2\lib\site-packages\jira\resilientsession.py", line 145, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "C:\Anaconda2\lib\site-packages\jira\resilientsession.py", line 55, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError
```
