### ISSUE TITLE
Error in the JQL Query: The character '%' is a reserved JQL character.

### ISSUE THREAD

**Issue by Johboh** [pycontribs/jira#336]
Hi.

I trying to do the following:
`result = jira.search_issues('filter=12345')`
But get the following:
`Traceback (most recent call last):
  File "playlist-lamps.py", line 84, in <module>
    main()
  File "playlist-lamps.py", line 46, in main
    be_issues = jira.search_issues('filter=23233', validate_query=False)
  File "c:\Python27\lib\site-packages\jira\client.py", line 1740, in search_issues
    issues = self._fetch_pages(Issue, 'issues', 'search', startAt, maxResults, search_params)
  File "c:\Python27\lib\site-packages\jira\client.py", line 390, in _fetch_pages
    resource = self._get_json(request_path, params=page_params, base=base)
  File "c:\Python27\lib\site-packages\jira\client.py", line 2165, in _get_json
    r = self._session.get(url, params=params)
  File "c:\Python27\lib\site-packages\jira\resilientsession.py", line 149, in get
    return self.__verb('GET', url, **kwargs)
  File "c:\Python27\lib\site-packages\jira\resilientsession.py", line 145, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "c:\Python27\lib\site-packages\jira\resilientsession.py", line 56, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://jira.host.net/rest/api/2/search?jql=filter%253D12345&validateQuery=False&startAt=0&maxResults=50
        text: Error in the JQL Query: The character '%' is a reserved JQL character. You must enclose it in a string or use the escape '\u0025' instead. (line 1, character 7)`

Some double encoding is happening?

Jira module 1.0.9
Jira version: 7.1.9

**Comment by PrzemekWirkus** [comment]
I got (`{"errorMessages":["A value with ID '12345' does not exist for the field 'filter'."],"errors":{}}`):
```
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://jira-***************
    text: A value with ID '12345' does not exist for the field 'filter'.
```
when doing:
```python
result = jira.search_issues('filter=12345')
```

So maybe you wanna do something like:
```python
result = jira.search_issues('issue=12345')
```

---
Note that you do get `%` sign encoded in your REST API URL, see `filter%253D12345`, where `%25` is `\u0025` -> `%` character.

Your url: `https://jira-***.com/rest/api/2/search?jql=filter%253D12345&validateQuery=False&startAt=0&maxResults=50`

My url: `https://jira-***.com/rest/api/2/search?jql=filter%3D12345&validateQuery=True&startAt=0&maxResults=50`

PS: I use lib 1.0.9.dev5. Hope this helps.

**Comment by PrzemekWirkus** [comment]
```python
result = jira.search_issues('filter=12345', validate_query=False)
```
returns `[]`.

I can see you set it to False too.

**Comment by moee** [comment]
I also experience the same problem as @Johboh 

`Error in the JQL Query: The character '%' is a reserved JQL character. You must enclose it in a string or use the escape '\u0025' instead.`

I'm trying to find a work around, but so far no luck
