### ISSUE TITLE
unexpected keyword functions of lib.jira object

### ISSUE THREAD

**Issue by krlng** [pycontribs/jira#337]
Running this in Python3:
```
from lib.jira import JIRA
username='xx'
password='xx'
server='https://jira.xx.de'
auth = (username, password)
jira = JIRA(server=server, basic_auth=auth)
boards = jira.boards(type='scrum')
```

gives me an error about wrong keywords. Same problem occurs to other functions and keywords of jira: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/lib/jira/client.py", line 91, in wrapper
    result = func(*arg_list, **kwargs)
TypeError: boards() got an unexpected keyword argument 'type'
```

**Comment by hdost** [comment]
First problem seems to be at line 1 `from lib.jira import JIRA` => `from jira import JIRA`

After that difference, unable to replicate issue.
