### ISSUE TITLE
Apparent regression in JIRA() when using basic_auth.  AttributeError: 'bool' object has no attribute 'error'

### ISSUE THREAD

**Issue by eanxgeek** [pycontribs/jira#353]
Recently hit this error with code that was working up until 02/26/2017.  Starting today I receive the following error in both python2 and python3 when attempting to connect to https://issues.jboss.org using basic_auth.

```
>>> jira = JIRA(options,basic_auth=(user, password))
WARNING:root:Bug https://jira.atlassian.com/browse/JRA-59676 trying again...
WARNING:root:Bug https://jira.atlassian.com/browse/JRA-59676 trying again...
WARNING:root:Bug https://jira.atlassian.com/browse/JRA-59676 trying again...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/jira/client.py", line 319, in __init__
    self._version = tuple(si['versionNumbers'])
KeyError: 'versionNumbers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/jira/client.py", line 321, in __init__
    logging.error("invalid server_info: %s", si)
AttributeError: 'bool' object has no attribute 'error'
```

**Comment by eanxgeek** [comment]
Issue was apparently in the REST api of our jira instance.  Our admins have addressed the issue and everything is working.

**Comment by sanjay75409** [comment]
I am getting the same from yesterday.
options = {'server':'https://myJiraServer/'}
jac = JIRA(options,basic_auth=(config.username, config.password))
