### ISSUE TITLE
oauth-dance fails with oauth valueError

### ISSUE THREAD

**Issue by ari** [pycontribs/jira#362]
This is run on OSX 10.12, with the jira module installed from pip as version 1.0.10.

```
$ jirashell -s https://foobar.com.au -od
Traceback (most recent call last):
  File "/usr/local/bin/jirashell", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/jira/jirashell.py", line 245, in main
    options['server'], oauth['consumer_key'], oauth['key_cert'], oauth['print_tokens'], options['verify'])
  File "/usr/local/lib/python2.7/site-packages/jira/jirashell.py", line 40, in oauth_dance
    server + '/plugins/servlet/oauth/request-token', verify=verify, auth=oauth)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 299, in prepare
    self.prepare_auth(auth, url)
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 494, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python2.7/site-packages/requests_oauthlib/oauth1_auth.py", line 88, in __call__
    unicode(r.url), unicode(r.method), None, r.headers)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth1/rfc5849/__init__.py", line 313, in sign
    ('oauth_signature', self.get_oauth_signature(request)))
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth1/rfc5849/__init__.py", line 128, in get_oauth_signature
    uri, headers, body = self._render(request)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth1/rfc5849/__init__.py", line 210, in _render
    request.oauth_params, request.headers, realm=realm)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth1/rfc5849/utils.py", line 31, in wrapper
    return target(params, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth1/rfc5849/parameters.py", line 57, in prepare_headers
    escaped_value = utils.escape(value)
  File "/usr/local/lib/python2.7/site-packages/oauthlib/oauth1/rfc5849/utils.py", line 56, in escape
    'Got %s of type %s.' % (u, type(u)))
ValueError: Only unicode objects are escapable. Got None of type <type 'NoneType'>.
```

**Comment by ari** [comment]
Turns out that to make -od work requires a bunch of other parameters. So the task here is that the library should return a more useful error message.

**Comment by neuromusic** [comment]
any tips on the other parameters -od needs?

**Comment by ari** [comment]
From memory it needed a keyfile and the server URL. I was expecting from the docs that -od would prompt you along the way for the various things it needed and create the key pair.

**Comment by k1-hedayati** [comment]
any update on this? can't login to jira

**Comment by k1-hedayati** [comment]
* Create a public key pair using `openssl`
  * `openssl genrsa -out private.pem 2048`
  * `openssl rsa -in private.pem -outform PEM -pubout -out public.pem`
* Create an application in JIRA, enter random url, go to incoming oauth tab, type consumer key as you like, enter public key created in previous state, save it.
* Run `jirashell -s https:/awesome.company.com -od -ck "<consumer key>" -k private.pem -pt` and follow instructions
