### ISSUE TITLE
update() got multiple values for keyword argument 'fields'

### ISSUE THREAD

**Issue by i11** [pycontribs/jira#39]
Hi!

I'm having trouble issuing an update call for updating summary, description or applying lablels.
Running with virtualenv on RHEL 6.4. 
```
>>> issue.update(summary="I'm different!", description='Changed the summary to be different.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/virtualenv/py2.6-my-virtualenv-2.0.1.25/lib/python2.6/site-packages/jira/resources.py", line 331, in update
    super(Issue, self).update(fields=None, async=async, jira=jira, **data)
TypeError: update() got multiple values for keyword argument 'fields'
```

```
>>> issue.update(labels=['AAA', 'BBB'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/virtualenv/py2.6-my-virtualenv-2.0.1.25/lib/python2.6/site-packages/jira/resources.py", line 331, in update
    super(Issue, self).update(fields=None, async=async, jira=jira, **data)
TypeError: update() got multiple values for keyword argument 'fields'
```

**Comment by JohnTheodore** [comment]
This is fixed in the latest version of the pypi package. Are you running jira 0.41?

**Comment by i11** [comment]
I was using 0.35. It doesn't persist with 0.47. Thanks!
