### ISSUE TITLE
update_filter uses the filter label instead of filter_id to make its call

### ISSUE THREAD

**Issue by abovetheborg** [pycontribs/jira#428]
# Summary:
This code below throws an error "JiraError HTTP 404" because the REST call being made uses the filter name and not the filter_id

> jira.exceptions.JIRAError: JiraError HTTP 404 url: https://jirainstance/rest/api/2/filter/Last_Comment_by_me

According to the documentation I've found here: https://docs.atlassian.com/jira/REST/cloud/?_ga=2.171222304.1220393959.1503523276-1106589769.1489452182#api/2/filter-editFilter

The API is expecting an ID 

> PUT /rest/api/2/filter/{id}

# Details
## Code
```
FilterID='44267'
CompleteFilter= 'issuekey in (' + Filterstr + ')'    #Filterstr is a string
allo=plmjira.update_filter(allo,FilterID, jql=CompleteFilter)
```

## Call Traceback

```
Traceback (most recent call last):
  File "C:\Users\me\.p2\pool\plugins\org.python.pydev_5.9.2.201708151115\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:\Users\me\eclipse-workspace\JIRA Vicarium\src\GetLastCommentedJiraForUser.py", line 62, in <module>
    allo=plmjira.update_filter(allo,FilterID, jql=CompleteFilter)
  File "C:\Program Files\Python36\lib\site-packages\jira\client.py", line 747, in update_filter
    filter = self.filter(filter_id)
  File "C:\Program Files\Python36\lib\site-packages\jira\client.py", line 701, in filter
    return self._find_for_resource(Filter, id)
  File "C:\Program Files\Python36\lib\site-packages\jira\client.py", line 2185, in _find_for_resource
    resource.find(id=ids, params=params)
  File "C:\Program Files\Python36\lib\site-packages\jira\resources.py", line 197, in find
    self._load(url, params=params)
  File "C:\Program Files\Python36\lib\site-packages\jira\resources.py", line 313, in _load
    r = self._session.get(url, headers=headers, params=params)
  File "C:\Program Files\Python36\lib\site-packages\jira\resilientsession.py", line 150, in get
    return self.__verb('GET', url, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\jira\resilientsession.py", line 146, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\jira\resilientsession.py", line 56, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError: JiraError HTTP 404 url: https://jirainstance/rest/api/2/filter/Last_Comment_by_me
	
	response headers = {'X-AREQUESTID': '1140x15783857x2', 'X-ASESSIONID': 't3id2g', 'X-ASEN': 'SEN-2827701', 'X-Seraph-LoginReason': 'OK', 'X-AUSERNAME': 'me', 'Cache-Control': 'no-cache, no-store, no-transform', 'X-Content-Type-Options': 'nosniff', 'Content-Encoding': 'gzip', 'Vary': 'User-Agent', 'Content-Type': 'text/html;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Date': 'Thu, 24 Aug 2017 02:00:05 GMT'}
	response text = 
ERROR: Module: GetLastCommentedJiraForUser could not be imported (file: C:\Users\me\eclipse-workspace\JIRA Vicarium\src\GetLastCommentedJiraForUser.py).
```

Note: obfuscated the domain & username

**Comment by abovetheborg** [comment]
Well. It seems that there is no bugs. This is a user error (mine).  Closing
