### ISSUE TITLE
UnicodeDecodeError when using jira 1.0.11 as setup.py dependency

### ISSUE THREAD

**Issue by melkamar** [pycontribs/jira#506]
My project's `python setup.py install` started crashing due to UnicodeDecodeErrors caused by using latest `jira` dependency. 

**Forcing an older version via `jira==1.0.10` fixes the problem, which leads me to believe this is a bug somewhere in 1.0.11.**

The error stack trace is long, below is just an excerpt (the rest is just nested exceptions). 

The error is present on Windows, I did not try Linux as my project is Windows-specific.

```
Installed c:\users\melka\appdata\local\temp\4\easy_install-3b7jkzk6\jira-1.0.11\.eggs\pbr-3.1.1-py3.6.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "c:\users\melka\appdata\local\temp\4\easy_install-3b7jkzk6\jira-1.0.11\.eggs\pbr-3.1.1-py3.6.egg\pbr\core.py", li
ne 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "c:\users\melka\appdata\local\temp\4\easy_install-3b7jkzk6\jira-1.0.11\.eggs\pbr-3.1.1-py3.6.egg\pbr\util.py", li
ne 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "c:\users\melka\appdata\local\temp\4\easy_install-3b7jkzk6\jira-1.0.11\.eggs\pbr-3.1.1-py3.6.egg\pbr\hooks\__init
__.py", line 25, in setup_hook
    metadata_config.run()
  File "c:\users\melka\appdata\local\temp\4\easy_install-3b7jkzk6\jira-1.0.11\.eggs\pbr-3.1.1-py3.6.egg\pbr\hooks\base.p
y", line 27, in run
    self.hook()
  File "c:\users\melka\appdata\local\temp\4\easy_install-3b7jkzk6\jira-1.0.11\.eggs\pbr-3.1.1-py3.6.egg\pbr\hooks\metada
ta.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "c:\users\melka\appdata\local\temp\4\easy_install-3b7jkzk6\jira-1.0.11\.eggs\pbr-3.1.1-py3.6.egg\pbr\packaging.py
", line 737, in get_version
    version = _get_version_from_pkg_metadata(package_name)
  File "c:\users\melka\appdata\local\temp\4\easy_install-3b7jkzk6\jira-1.0.11\.eggs\pbr-3.1.1-py3.6.egg\pbr\packaging.py
", line 705, in _get_version_from_pkg_metadata
    pkg_metadata = email.message_from_file(pkg_metadata_file)
  File "D:\storage\tools\Python\3.6.1\lib\email\__init__.py", line 54, in message_from_file
    return Parser(*args, **kws).parse(fp)
  File "D:\storage\tools\Python\3.6.1\lib\email\parser.py", line 54, in parse
    data = fp.read(8192)
  File "D:\storage\tools\Python\3.6.1\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 6863: character maps to <undefined>
```

Following the position of the character in the PKG-INFO file (as hinted further in the stack trace), it is a japanese symbol (the line below `contributing.rst: Update JIRA community link`).

**Comment by ssbarnea** [comment]
1.0.11 was removed from PYPI, please use 1.0.14 which had this fixed.
