### ISSUE TITLE
AttributeError: 'module' object has no attribute 'kqueue'

### ISSUE THREAD

**Issue by xiaoluosun** [pycontribs/jira#515]
```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gunicorn/workers/async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/Library/Python/2.7/site-packages/gunicorn/workers/ggevent.py", line 152, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/Library/Python/2.7/site-packages/gunicorn/workers/async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Library/Python/2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/flask_cache/__init__.py", line 297, in decorated_function
    rv = f(*args, **kwargs)
  File "/Users/sun/Documents/PycharmProjects/testcenter/backend/app/index/indexviews.py", line 48, in search_unresolved_issues
    results = get_unresolved_issues()
  File "/Users/sun/Documents/PycharmProjects/testcenter/backend/app/index/services/searchjira.py", line 94, in get_unresolved_issues
    versions = _JIRA.project_versions(de_dao)
  File "/Library/Python/2.7/site-packages/jira/client.py", line 133, in wrapper
    result = func(*arg_list, **kwargs)
  File "/Library/Python/2.7/site-packages/jira/client.py", line 1825, in project_versions
    r_json = self._get_json('project/' + project + '/versions')
  File "/Library/Python/2.7/site-packages/jira/client.py", line 2355, in _get_json
    r = self._session.get(url, params=params)
  File "/Library/Python/2.7/site-packages/jira/resilientsession.py", line 150, in get
    return self.__verb('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/jira/resilientsession.py", line 124, in __verb
    response = method(url, timeout=self.timeout, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 588, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 241, in _get_conn
    if conn and is_connection_dropped(conn):
  File "/Library/Python/2.7/site-packages/urllib3/util/connection.py", line 27, in is_connection_dropped
    return bool(wait_for_read(sock, timeout=0.0))
  File "/Library/Python/2.7/site-packages/urllib3/util/wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)
  File "/Library/Python/2.7/site-packages/urllib3/util/wait.py", line 22, in _wait_for_io_events
    with DefaultSelector() as selector:
  File "/Library/Python/2.7/site-packages/urllib3/util/selectors.py", line 581, in DefaultSelector
    return _DEFAULT_SELECTOR()
  File "/Library/Python/2.7/site-packages/urllib3/util/selectors.py", line 461, in __init__
    self._kqueue = select.kqueue()
AttributeError: 'module' object has no attribute 'kqueue'
```

**Comment by hdost** [comment]
Without a code example to reproduce the error, this is not actionable.
