### ISSUE TITLE
can't use pip install jira

### ISSUE THREAD

**Issue by jackiezero** [pycontribs/jira#554]
I used pip3 install jira  but there  have a SSL  problem .
then I download jira-1.0.15.tar.gz  to install  have the same problem

```
MacBook-Pro-2  ~  pip3 install jira
Collecting jira
  Could not fetch URL https://pypi.python.org/simple/jira/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:720) - skipping
  Could not find a version that satisfies the requirement jira (from versions: )
No matching distribution found for jira
 ✘ MacBook-Pro-2  ~  pip3  --trusted-host pypi.python.org install jira
Collecting jira
  Could not fetch URL https://pypi.python.org/simple/jira/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:720) - skipping
  Could not find a version that satisfies the requirement jira (from versions: )
No matching distribution found for jira
```

```python setup.py install
Download error on https://pypi.python.org/simple/sphinx/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'sphinx' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
No local packages or download links found for sphinx>=1.6.5
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    pbr=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 268, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 843, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1088, in best_match
    return self.obtain(req, installer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1100, in obtain
    return installer(requirement)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 380, in fetch_build_egg
    return cmd.easy_install(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 632, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('sphinx>=1.6.5')
```

**Comment by jackiezero** [comment]
# @dbaxa     I have succeed with win10 used same version pip   ,but it's error in macbook
``` pip 9.0.1 from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (python 3.5)```

**Comment by ssbarnea** [comment]
I am going to close this because I am 99% sure this is pypi related due to the backend changes made this week. Probably you already sorted it by now.
