### ISSUE TITLE
Incompatibility with Python 3.7

### ISSUE THREAD

**Issue by shoelzle** [pycontribs/jira#633]
**Describe the bug**
With python 3.7 the jira python module is not usable.

**To Reproduce**
```
$ python3
Python 3.7.0 (default, Jun 29 2018, 20:13:13)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jira
```

**Expected behavior**
Successful import

**Stack Trace**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shoelzle/Library/Python/3.7/lib/python/site-packages/jira/__init__.py", line 10, in <module>
    from jira.client import Comment  # noqa: E402
  File "/Users/shoelzle/Library/Python/3.7/lib/python/site-packages/jira/client.py", line 337
    validate=False, get_server_info=True, async=False, logging=True, max_retries=3, proxies=None,
                                              ^
SyntaxError: invalid syntax
```

**Version Information**
Python Interpreter: 3.7.0
jira-python: 1.0.15
OS: macOS High Sierra 10.13.6

**Comment by hdost** [comment]
Fix is already in master, will be released with 2.0

**Comment by hdost** [comment]
@ssbarnea going to keep open until master released because we've gotten 5 of these and it's technically not closed since it's not released.

**Comment by asqui** [comment]
LOL, maybe we need a slack channel to help with communication/coordination around this project?

**Comment by ssbarnea** [comment]
@asqui We do have an irc channel ``#pycontribs`` but somehow I am the only one on it. You are more than welcome to join there, I am permanently connected.

**Comment by asqui** [comment]
IRC! That's a bit oldschool isn't it? :-D Do they make mobile clients for that?

Should we try something a bit more modern and organised? Drop me an email at pycontribs@danielfortunov.com with your preferred email address and I'll invite you to a Zulip organisation and we can try it out.

PS. I noticed! Great work.

**Comment by ssbarnea** [comment]
@asqui It is old school but it it also defacto standard for open source projects. I kinda hate irc myself but if you are looking for a more modern experience use matrix/riot.io to connect to irc, it will give you an experience very close to slack: https://riot.im -- with mobile and desktop clients too,... which do not make you want to double your RAM on it ;)
