### ISSUE TITLE
Pip install git+https://github.com/pycontribs/jira.git fails

### ISSUE THREAD

**Issue by frank-belldev** [pycontribs/jira#647]
When I try to install lira by using this git repo, I am getting this error.

123$ pip install git+https://github.com/pycontribs/jira.git

```
Collecting git+https://github.com/pycontribs/jira.git
  Cloning https://github.com/pycontribs/jira.git to /private/var/folders/m1/476d474n4dz1rdn2scsj06y40000gn/T/pip-req-build-ZtmyqA
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/sphinx/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'sphinx' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    No local packages or working download links found for sphinx>=1.6.5
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/m1/476d474n4dz1rdn2scsj06y40000gn/T/pip-req-build-ZtmyqA/setup.py", line 15, in <module>
        pbr=True)
      File "/Users/123/Development/Python/myproject/src/env/lib/python2.7/site-packages/setuptools/__init__.py", line 130, in setup
        _install_setup_requires(attrs)
      File "/Users/123/Development/Python/myproject/src/env/lib/python2.7/site-packages/setuptools/__init__.py", line 125, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/123/Development/Python/myproject/src/env/lib/python2.7/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/123/Development/Python/myproject/src/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 773, in resolve
        replace_conflicting=replace_conflicting
      File "/Users/123/Development/Python/myproject/src/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1056, in best_match
        return self.obtain(req, installer)
      File "/Users/123/Development/Python/myproject/src/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1068, in obtain
        return installer(requirement)
      File "/Users/123/Development/Python/myproject/src/env/lib/python2.7/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/123/Development/Python/myproject/src/env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 670, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('sphinx>=1.6.5')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/m1/476d474n4dz1rdn2scsj06y40000gn/T/pip-req-build-ZtmyqA/
```

Not sure how to run pip install by using this git repo...

**Comment by hdost** [comment]
http://mindtrove.info/til-pip-git/

**Comment by frank-belldev** [comment]
I already checked it, but it's not helpful in this case.
I've got success by doing the same thing several days ago, but now it does not work.
Would you please check it by yourself if you can't believe ?
