### ISSUE TITLE
async causes comment.delete() to break

### ISSUE THREAD

**Issue by jefft** [pycontribs/jira#700]
**Describe the bug**
When initially connecting to JIRA ``async: True``, later calls to comment.delete() fail with an ``AttributeError: 'function' object has no attribute 'delete'``. The same operation works fine with async turned off.

**To Reproduce**

Connect to JIRA with any authentication method (I'm using oauth below), with ``'async': True`` option. Find a comment. Try to delete it as per the [docs](https://jira.readthedocs.io/en/master/examples.html#comments):
```
#!/usr/bin/env python3

from myapp import cfg
from jira import JIRA

def connectjira():
    options = {
            'server': cfg.server
            ,'async': True
            }

    oauth={
            'access_token': cfg.access_token
            ,'access_token_secret': cfg.access_token_secret
            ,'consumer_key': cfg.consumer_key
            ,'key_cert': open(cfg.key_cert_file, 'r').read()
            }

    return JIRA(options=options, oauth=oauth)

jira = connectjira()
issue = jira.issue('BC-20')
comments = issue.fields.comment.comments
print(f"{issue} has {len(comments)} comments")
if len(comments)>0:
    firstcomment = comments[0]
    print(f"First comment: {firstcomment}")
    firstcomment.delete()
```

1. Any additional steps or considerations that happen before or after.

**Expected behavior**
Comment should be deleted.

**Stack Trace**
```
$ ./testdel.py 
BC-20 has 1 comments
First comment: 63124
Traceback (most recent call last):
  File "./testdel.py", line 28, in <module>
    firstcomment.delete()
  File "/home/jturner/testdel/venv/src/jira/jira/resources.py", line 365, in delete
    threaded_requests.delete(url=self.self, params=params))
AttributeError: 'function' object has no attribute 'delete'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```
```


**Version Information**
Python Interpreter: 3.6.6
jira-python: 823820d99712c13350735104db1703c8a1ff5705 (29/Sep/18)
OS: Linux

**Comment by rickatnight11** [comment]
`<ISSUE>.delete()` also fails with `async`:

```
options = {
    'server': 'https://<jira-server>',
    'async': True
}
jira = JIRA(options=options, basic_auth=('<user>', '<password>'))
issues = jira.search_issues('project = TEST', fields='key', maxResults=10000)

for issue in issues:
    issue.delete()
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/rickatnight11/.local/lib/python2.7/site-packages/jira/jirashell.pyc in <module>()
----> 1 issue.delete()

/home/rickatnight11/.local/lib/python2.7/site-packages/jira/resources.pyc in delete(self, deleteSubtasks)
    504         :type deleteSubtasks: bool
    505         """
--> 506         super(Issue, self).delete(params={'deleteSubtasks': deleteSubtasks})
    507
    508     def permalink(self):

/home/rickatnight11/.local/lib/python2.7/site-packages/jira/resources.pyc in delete(self, params)
    309                 self._session._async_jobs = set()
    310             self._session._async_jobs.add(
--> 311                 threaded_requests.delete(url=self.self, params=params))
    312         else:
    313             return self._session.delete(url=self.self, params=params)

AttributeError: 'function' object has no attribute 'delete'
```
