### ISSUE TITLE
Transitioning issues in for loop fails

### ISSUE THREAD

**Issue by pkaramol** [pycontribs/jira#740]
**Describe the bug**
I am filtering some issues and adding them in a list.
When iterating through the list, one of the transitions __seems to__ fail (but is actually implemented) with `Invalid transition name. Start Work` (although the transition is definately valid)  and the other one is never carried out.

If I re-run the script, the one that was not performed, is now carried out.

If the list contains only one issue, the transition always succeeds.

**To Reproduce**
```python
def open_client_session():
    options = { 'server': JIRA_DOMAIN }
    return JIRA(options=options, timeout=10, max_retries=1, basic_auth=(JIRA_USER, JIRA_TOKEN))

def update_issues(sprintname, fixVersion):

    jira_client = None

    jira_client = open_client_session()

    issue_list = []

    jql_expression = 'fixVersion="{}" AND sprint in openSprints() AND status={} AND (issuetype={} OR issuetype={})'.format(FIX_VERSION, TEST_STATUS_FROM, TEST_ISSUETYPE1, TEST_ISSUETYPE2)

    issues = jira_client.search_issues(jql_expression, maxResults=False, fields=["status", "issuetype", SPRINT_CUSTOM_FIELD])

    for value in issues:
        sprint_list = (getattr(value.fields, SPRINT_CUSTOM_FIELD))
        if sprint_list:
            for sprint_item in sprint_list:
                sprint_name = re.findall(r"name=[^,]*", str(getattr(value.fields, SPRINT_CUSTOM_FIELD)[0]))
                sprint_name = sprint_name[0].split("=")[1]
                # sprint_state = re.findall(r"state=[^,]*", str(getattr(value.fields, SPRINT_CUSTOM_FIELD)[0]))
                if sprint_name == sprintname:
                    issue_list.append(value)


    for item in issue_list:
        print("Issue to be affected: {}, with old status {}".format(str(item), item.fields.status.name))
        jira_client.transition_issue(str(value), "Start Work")
        time.sleep(3)
        print("Issue {} now in status {}".format(str(item), item.fields.status.name))



if __name__ == "__main__":
    update_issues("Test Sprint 1", "1.0.0")

```
**Expected behavior**
All issues retrieved should be transitioned in the desired state;

**Stack Trace**
```python
Issue to be affected: TESTSP-26, with old status Open
Issue TESTSP-26 now in status Open
Issue to be affected: TESTSP-25, with old status Open
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jira/client.py", line 1554, in transition_issue
    transitionId = int(transition)
ValueError: invalid literal for int() with base 10: 'Start Work'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./move_issues.py", line 60, in <module>
    update_issues("Test Sprint 1", "Reopened", "Closed", "1.0.0")
  File "./move_issues.py", line 53, in update_issues
    jira_client.transition_issue(str(value), "Start Work")
  File "/usr/local/lib/python3.6/dist-packages/jira/client.py", line 126, in wrapper
    result = func(*arg_list, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jira/client.py", line 1559, in transition_issue
    raise JIRAError("Invalid transition name. %s" % transition)
jira.exceptions.JIRAError: JiraError HTTP Invalid transition name. Start Work
	

```

**Version Information**
Python Interpreter:
```
$ /usr/bin/python3 --version
Python 3.6.7
```
jira-python:
```
$ pip freeze | grep jira
jira==2.0.0
```
OS: 
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by saloni-canva** [comment]
Hi @pkaramol were you able to get this to work?
