### ISSUE TITLE
JIRA() instance is not notifying when token it's ok but user is not

### ISSUE THREAD

**Issue by valerybriz** [pycontribs/jira#808]
**Description of the bug**
When a user tries to login with a wrong or inexistent User or if it doesn't has the required permissions to perform operations and a correct Token the instantiation won't raise an error or any kind of message.
So after this when you try to perform an action with this jira client authenticated it won't work and also it will show an inaccurate error message.

**To Reproduce**

```
from jira import JIRA
# This call should respond with an error when the user is incorrect
authed_jira = JIRA(server="https://<YOUR DOMAIN>.atlassian.net/", basic_auth=("<WRONG_USER>", "<CORRECT_TOKEN>"))

issues_in_proj = authed_jira.search_issues(jql_str='project = "<PROJECT_NAME>"')

```
1. The user for the authentication most be incorrect or not existent on the account/project
2. The Token has to be correct and enabled

**Expected behavior**
When you try to instantiate JIRA() with an incorrect user it should respond with an error message.

**Stack Trace**
This is the traceback of the error it throws when executing the code noted above:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    issues_in_proj = authed_jira.search_issues(jql_str='project = "PrOject" ORDER BY created')
  File "/Users/val002/Documents/venvs/drf_test/lib/python3.7/site-packages/jira/client.py", line 2109, in search_issues
    issues = self._fetch_pages(Issue, 'issues', 'search', startAt, maxResults, search_params)
  File "/Users/val002/Documents/venvs/drf_test/lib/python3.7/site-packages/jira/client.py", line 575, in _fetch_pages
    resource = self._get_json(request_path, params=page_params, base=base)
  File "/Users/val002/Documents/venvs/drf_test/lib/python3.7/site-packages/jira/client.py", line 2549, in _get_json
    r = self._session.get(url, params=params)
  File "/Users/val002/Documents/venvs/drf_test/lib/python3.7/site-packages/jira/resilientsession.py", line 151, in get
    return self.__verb('GET', url, **kwargs)
  File "/Users/val002/Documents/venvs/drf_test/lib/python3.7/site-packages/jira/resilientsession.py", line 147, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/Users/val002/Documents/venvs/drf_test/lib/python3.7/site-packages/jira/resilientsession.py", line 57, in raise_on_error
  File "/Users/val002/Documents/venvs/drf_test/lib/python3.7/site-packages/jira/resilientsession.py", line 57, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://prescrypto.atlassian.net/rest/api/2/search?jql=project+%3D+%22PrOject%22+ORDER+BY+created&startAt=0&validateQuery=True&maxResults=50
        text: The value 'PrOject' does not exist for the field 'project'.
        
'max-ag response headers = {'Server': 'AtlassianProxy/1.15.8.1', 'Cache-Control': 'no-cache, no-store, no-transform', 'Content-Type': 'application/json;charset=UTF-8', 'Strict-Transport-Security': e=315360000; includeSubDomains; preload', 'Date': 'Tue, 25 Jun 2019 20:37:11 GMT', 'ATL-TraceId': 'ca56e34e20f9a105', 'X-AREQUESTID': 'de36b32f-961e-499b-9492-8f06ac3751aa', 'X-XSS-Protection': '1;
 mode=block', 'Transfer-Encoding': 'chunked', 'Timing-Allow-Origin': '*', 'X-Content-Type-Options': 'nosniff', 'Connection': 'close'}
        response text = {"errorMessages":["The value 'PrOject' does not exist for the field 'project'."],"warningMessages":[]}

```

**Version Information**
Python Interpreter: 3.7
jira-python: 2.0
OS: MACOS 10.13.6

**Comment by ebarojas** [comment]
Apparently token only works with admin emails. In any case, if you're updating a basic http authentication implementation, you need to update the user name too, and 

1. Error handling is very misleading.
2. Documentation does not explain this.
