### ISSUE TITLE
The error generated as a result of Basic Authentication failure is not indicative of root cause

### ISSUE THREAD

**Issue by kamal2222ahmed** [pycontribs/jira#887]
Before raising any bug be sure that you used the latest release and that it still reproduces with the latest master. No other version is supported.

**Describe the bug**
Here is a sample python script to login ot Jira Server and get few fields related to an issue

```
from jira import JIRA
def main():
   options = {'server':"https://jira.boozallencsn.com/" }
   jira = JIRA(options, basic_auth=('svc_username', 'svc_password'))
   issue = jira.issue('XXXX-10085')
   print (issue.fields.project.key)
   print (issue.fields.issuetype.name)
   print (issue.fields.reporter.displayName)
   print (issue.fields.summary)
   print (issue.fields.project.id)

if __name__== "__main__" :
     main()
```

If the account is inactive, we should get an indication related to the account, but I get:

```
WARNING:root:Bug https://jira.atlassian.com/browse/JRA-59676 trying again...
WARNING:root:Bug https://jira.atlassian.com/browse/JRA-59676 trying again...
WARNING:root:Bug https://jira.atlassian.com/browse/JRA-59676 trying again...
Traceback (most recent call last):
  File "/Users/syedahmed/ANACONDA/anaconda3/lib/python3.7/site-packages/jira/client.py", line 474, in __init__
    self._version = tuple(si['versionNumbers'])
KeyError: 'versionNumbers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jira_test.py", line 13, in <module>
    main()
  File "jira_test.py", line 4, in main
    jira = JIRA(options, basic_auth=('svc_username', 'sac_password'))
  File "/Users/syedahmed/ANACONDA/anaconda3/lib/python3.7/site-packages/jira/client.py", line 476, in __init__
    logging.error("invalid server_info: %s", si)
AttributeError: 'bool' object has no attribute 'error'
```
**To Reproduce**
run the above python script, once you get the proper credentials
```

**Version Information**
Python Interpreter: Python 3.8.0
jira-python: pkg_resources.get_distribution("jira").version
'2.0.0'
OS: Mac OSX 10.14.5
IPython (Optional): 
Other Dependencies:


**Additional context**
none

**Comment by jhermann** [comment]
There are at least 2 problems here:
* The ticket link in the warning is gone or protected, i.e. the warning is pretty much useless
* The global "logging" is shadowed by an argument, thus the "bool has no error" -- the project should use pylint or flake8 to avoid these things

**Comment by jhermann** [comment]
Also, this is a dupe of #298
