### ISSUE TITLE
Need help authenticating properly with an API token

### ISSUE THREAD

**Issue by pabgan** [pycontribs/jira#952]
I am unable to create a simple script, sorry.

Everything I need works fine in the `jirashell`.
```
$ jirashell -s https://my-comp.atlassian.net -u 'user@my-comp.com' -p "plaintextAPItoken"

*** JIRA shell active; client is in 'jira'. Press Ctrl-D to exit.

In [1]: issue = jira.issue('DSLE-21230')

In [2]: print(issue.fields.summary)
Common: merge dcpc_snmp_rfc2662 into snmp_common_util
```
But my simple script:
```
$ cat jira-turbo.py
#!/usr/bin/python3
from collections import Counter
from jira import JIRA

# By default, the client will connect to a Jira instance started from the Atlassian Plugin SDK.
# See
# https://developer.atlassian.com/display/DOCS/Installing+the+Atlassian+Plugin+SDK
# for details.
jac = JIRA('https://my-comp.atlassian.net', basic_auth=('user@my-comp.net', "plaintextAPItoken"))

issue=jac.issue('DSLE-21230')
print(issue.fields.summary)
```
does not have permissions for that:
```
$ ./jira-turbo.py
Traceback (most recent call last):
  File "./jira-turbo.py", line 18, in <module>
    issue=jac.issue('DSLE-21230')
  File "/home/user/.local/lib/python3.6/site-packages/jira/client.py", line 1071, in issue
    issue.find(id, params=params)
  File "/home/user/.local/lib/python3.6/site-packages/jira/resources.py", line 201, in find
    self._load(url, params=params)
  File "/home/user/.local/lib/python3.6/site-packages/jira/resources.py", line 316, in _load
    r = self._session.get(url, headers=headers, params=params)
  File "/home/user/.local/lib/python3.6/site-packages/jira/resilientsession.py", line 151, in get
    return self.__verb('GET', url, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/jira/resilientsession.py", line 147, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/jira/resilientsession.py", line 57, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
jira.exceptions.JIRAError: JiraError HTTP 404 url: https://my-comp.atlassian.net/rest/api/2/issue/DSLE-21230
        text: Issue does not exist or you do not have permission to see it.

        response headers = {'Server': 'AtlassianProxy/1.15.8.1', 'Vary': 'Accept-Encoding', 'Cache-Control': 'no-cache, no-store, no-transform', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': 'max-age=315360000; includeSubDomains; preload', 'Date': 'Tue, 07 Jul 2020 08:47:25 GMT', 'ATL-TraceId': '0915199bd5734db8', 'X-AREQUESTID': '06c237e4-b3a5-4586-a62d-850a27cf97b9', 'X-XSS-Protection': '1; mode=block', 'Transfer-Encoding': 'chunked', 'Timing-Allow-Origin': '*', 'X-Content-Type-Options': 'nosniff', 'Micros-Issuer': 'micros/edge-authenticator', 'Connection': 'keep-alive', 'Expect-CT': 'report-uri="https://web-security-reports.services.atlassian.com/expect-ct-report/global-proxy", enforce, max-age=86400'}
        response text = {"errorMessages":["Issue does not exist or you do not have permission to see it."],"errors":{}}
```
Changing the password makes it fail with:
```
ARNING:root:Got recoverable error from GET https://my-comp.atlassian.net/rest/api/2/serverInfo, will retry [1/3] in 14.01382243613401s. Err: 401 Unauthorized
```
So I have no idea what is happening.

Thank you very much in advance.

**Comment by pabgan** [comment]
It somehow started working. Might be that I rebooted the computer and some cache was flushed or something.

Anyway, thanks for you work and sorry for the inconveniences.
